/**
 * AI Call Planner Proposal Generation API Endpoints
 *
 * POST /api/call-planner/drafts/[id]/generate-proposal - Generate proposal from draft
 *
 * The ProposalDraft create executes via Manifest runtime (magicToken is
 * generated by the command's uuid() builtin). Reads are direct tenant-scoped
 * Prisma queries (constitution §10).
 */

import { auth } from "@repo/auth/server";
import { database } from "@repo/database";
import { log } from "@repo/observability/log";
import { captureException } from "@sentry/nextjs";
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { resolveCurrentUser } from "@/app/lib/tenant";
import { runCommand } from "@/lib/manifest/execute-command";
import { generateProposalContent } from "../../../lib/proposal-generator";

export const runtime = "nodejs";

type Params = Promise<{ id: string }>;

/**
 * POST /api/call-planner/drafts/[id]/generate-proposal
 * Generate a proposal from a draft
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Params }
) {
  try {
    const { orgId, userId: clerkUserId } = await auth();
    if (!orgId || !clerkUserId) {
      return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;
    const user = await resolveCurrentUser(request);
    const tenantId = user.tenantId;
    const body = await request.json();

    const {
      clientEmail,
      clientPhone,
      includePricing = true,
      includeUpgrades = true,
    } = body as {
      clientEmail?: string;
      clientPhone?: string;
      includePricing?: boolean;
      includeUpgrades?: boolean;
    };

    // Read path: load the draft (no Prisma relations — flat keys only)
    const draft = await database.eventPlanningDraft.findFirst({
      where: {
        tenantId,
        id,
        deletedAt: null,
      },
    });

    if (!draft) {
      return NextResponse.json({ message: "Draft not found" }, { status: 404 });
    }

    // Generate proposal content (pure heuristics, no DB writes)
    const proposalContent = generateProposalContent(draft, {
      includePricing,
      includeUpgrades,
    });

    const title = `Proposal for ${draft.clientName || "Event"}${
      draft.eventType
        ? ` - ${draft.eventType.replace(/_/g, " ").toUpperCase()}`
        : ""
    }`;

    // Governed write: create the proposal draft via Manifest runtime.
    // JSON payload properties are JSON-as-string in the manifest contract;
    // magicToken/magicTokenExpiresAt are set inside the command (uuid(),
    // addDays(now(), 30)).
    const createResponse = await runCommand({
      entity: "ProposalDraft",
      command: "create",
      body: {
        draftId: draft.id,
        userId: user.id,
        title,
        clientName: draft.clientName ?? "",
        ...(clientEmail ? { clientEmail } : {}),
        ...(clientPhone ? { clientPhone } : {}),
        eventSummary: JSON.stringify(proposalContent.eventSummary),
        menuSections: JSON.stringify(proposalContent.menuSections),
        servicePlan: JSON.stringify(proposalContent.servicePlan),
        pricingBreakdown: JSON.stringify(proposalContent.pricingBreakdown),
        ...(proposalContent.timeline
          ? { timeline: JSON.stringify(proposalContent.timeline) }
          : {}),
        ...(proposalContent.upgradeOptions
          ? { upgradeOptions: JSON.stringify(proposalContent.upgradeOptions) }
          : {}),
        ...(proposalContent.visionSummary
          ? { visionSummary: proposalContent.visionSummary }
          : {}),
        ...(proposalContent.notes ? { notes: proposalContent.notes } : {}),
        ...(proposalContent.nextSteps
          ? { nextSteps: proposalContent.nextSteps }
          : {}),
      },
      user: { id: user.id, tenantId: user.tenantId, role: user.role },
    });
    if (!createResponse.ok) {
      return createResponse;
    }

    const payload = (await createResponse.json()) as {
      result?: {
        id?: string;
        title?: string;
        magicToken?: string;
        status?: string;
        magicTokenExpiresAt?: unknown;
      };
    };
    const proposal = payload.result ?? {};

    // NOTE: EventPlanningDraft.proposalId is NOT written here — no governed
    // command exposes it (flagged for a follow-up `linkProposal` command).
    // The linkage is preserved on the proposal side via ProposalDraft.draftId.

    return NextResponse.json({
      success: true,
      proposal: {
        id: proposal.id,
        draftId: draft.id,
        title: proposal.title ?? title,
        magicToken: proposal.magicToken,
        status: proposal.status ?? "draft",
        expiresAt: proposal.magicTokenExpiresAt ?? null,
      },
    });
  } catch (error) {
    captureException(error);
    log.error("Error generating proposal:", error);
    return NextResponse.json(
      { message: "Internal server error" },
      { status: 500 }
    );
  }
}
