// GENERATED by manifest:client (manifest/scripts/generate-capsule-client.mjs) — DO NOT EDIT.
// Auto-generated TypeScript types from Manifest IR
// DO NOT EDIT - This file is generated from .manifest source

export interface AdminChatParticipant {
  id: string;
  tenantId: string;
  threadId?: string;
  userId?: string;
  archivedAt: string;
  clearedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface AdminTask {
  id: string;
  tenantId: string;
  title?: string;
  description?: string;
  status?: string;
  priority?: string;
  category?: string;
  assignedTo?: string;
  dueDate: string;
  createdBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface AiEventSetupSession {
  id: string;
  tenantId: string;
  userId: string;
  originalInput?: string;
  parsedTitle?: string;
  parsedEventType?: string;
  parsedEventDate?: string;
  parsedGuestCount?: number;
  parsedVenueName?: string;
  parsedVenueAddress?: string;
  parsedNotes?: string;
  parsedTags?: string;
  status?: string;
  confidence?: number;
  missingFields?: string;
  suggestions?: string;
  createdEventId?: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface AlertsConfig {
  id: string;
  tenantId: string;
  channel?: string;
  destination?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AllergenWarning {
  id: string;
  tenantId: string;
  eventId?: string;
  dishId?: string;
  warningType?: string;
  allergens?: string;
  affectedGuests?: string;
  severity?: string;
  isAcknowledged?: boolean;
  acknowledgedBy?: string;
  acknowledgedAt: string;
  overrideReason?: string;
  resolved?: boolean;
  resolvedAt: string;
  escalatedAt: string;
  escalatedTo?: string;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ApiKey {
  id: string;
  tenantId: string;
  name?: string;
  keyPrefix?: string;
  hashedKey?: string;
  scopes: unknown[];
  lastUsedAt: string;
  expiresAt: string;
  revokedAt: string;
  createdByUserId?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BankAccount {
  id: string;
  tenantId: string;
  employeeId: string;
  accountHolderName: string;
  accountNumber: string;
  routingNumber: string;
  accountType?: string;
  bankName?: string;
  isDefault?: boolean;
  status?: string;
  verifiedAt: string;
  verificationFailedAt: string;
  verificationFailureReason?: string;
  createdAt: string;
  updatedAt: string;
}

export interface BattleBoard {
  id: string;
  tenantId: string;
  eventId?: string;
  boardName?: string;
  boardType?: string;
  schemaVersion?: string;
  boardData?: string;
  documentUrl?: string;
  sourceDocumentType?: string;
  documentImportedAt: string;
  status?: string;
  isTemplate?: boolean;
  description?: string;
  notes?: string;
  tags?: string;
  dishCount?: number;
  deletedAt: string;
  eventDate: string;
  clientId?: string;
  guestCount?: number;
  venueName?: string;
  venueAddress?: string;
  locationId?: string;
  inheritedContext?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Budget {
  id: string;
  tenantId: string;
  name: string;
  description?: string;
  fiscalYear?: number;
  totalAmount?: number;
  allocatedAmount?: number;
  spentAmount?: number;
  status?: string;
  category?: string;
  departmentId?: string;
  approvedBy?: string;
  approvedAt: string;
  lockedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BulkOrderRule {
  id: string;
  tenantId: string;
  catalogEntryId: string;
  ruleName?: string;
  minimumQuantity?: number;
  ruleType?: string;
  thresholdQuantity?: number;
  action?: string;
  discountPercent?: number;
  freeItemQuantity?: number;
  shippingIncluded?: boolean;
  priority?: number;
  effectiveFrom: string;
  effectiveTo: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CateringOrder {
  id: string;
  tenantId: string;
  orderNumber: string;
  customerId?: string;
  eventId?: string;
  orderStatus?: string;
  orderDate: string;
  deliveryDate: string;
  deliveryTime?: string;
  subtotalAmount?: number;
  taxAmount?: number;
  discountAmount?: number;
  serviceChargeAmount?: number;
  totalAmount?: number;
  depositRequired?: boolean;
  depositAmount?: number;
  depositPaid?: boolean;
  depositPaidAt: string;
  deliveredAt: string;
  prepStartedAt: string;
  venueName?: string;
  venueAddress?: string;
  venueCity?: string;
  venueState?: string;
  venueZip?: string;
  venueContactName?: string;
  venueContactPhone?: string;
  guestCount?: number;
  specialInstructions?: string;
  dietaryRestrictions?: string;
  staffRequired?: number;
  staffAssigned?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ChartOfAccount {
  id: string;
  tenantId: string;
  accountNumber?: string;
  accountName?: string;
  accountType?: string;
  parentId?: string;
  description?: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ClientInteraction {
  id: string;
  tenantId: string;
  clientId?: string;
  leadId?: string;
  employeeId?: string;
  interactionType?: string;
  interactionDate: string;
  subject?: string;
  description?: string;
  followUpDate: string;
  followUpCompleted?: boolean;
  status?: string;
  priority?: string;
  escalatedAt: string;
  escalatedTo?: string;
  correlationId?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Client {
  id: string;
  tenantId: string;
  clientType?: string;
  companyName?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  website?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  stateProvince?: string;
  postalCode?: string;
  countryCode?: string;
  defaultPaymentTerms?: number;
  taxExempt?: boolean;
  taxId?: string;
  notes?: string;
  tags: unknown[];
  source?: string;
  assignedTo?: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ClientContact {
  id: string;
  tenantId: string;
  clientId: string;
  firstName?: string;
  lastName?: string;
  title?: string;
  email?: string;
  phone?: string;
  phoneMobile?: string;
  isPrimary?: boolean;
  isBillingContact?: boolean;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ClientPreference {
  id: string;
  tenantId: string;
  clientId: string;
  preferenceType?: string;
  preferenceKey?: string;
  preferenceValue?: string;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CollectionCase {
  id: string;
  tenantId: string;
  invoiceId?: string;
  invoiceNumber?: string;
  eventId?: string;
  clientId?: string;
  clientName?: string;
  originalAmount?: number;
  outstandingAmount?: number;
  collectedAmount?: number;
  status?: string;
  priority?: string;
  dunningStage?: string;
  daysOverdue?: number;
  agingBucket?: string;
  assignedTo?: string;
  assignedAt: string;
  hasPaymentPlan?: boolean;
  paymentPlanId?: string;
  nextPaymentDue: string;
  isDisputed?: boolean;
  disputeReason?: string;
  disputeResolvedAt: string;
  isEscalatedToLegal?: boolean;
  legalCaseNumber?: string;
  legalFirm?: string;
  notes?: string;
  internalNotes?: string;
  lastActivityAt: string;
  metadata?: string;
  resolvedAt: string;
  closedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CollectionAction {
  id: string;
  tenantId: string;
  caseId?: string;
  actionType?: string;
  direction?: string;
  status?: string;
  contactedBy?: string;
  contactName?: string;
  contactMethod?: string;
  subject?: string;
  description?: string;
  outcome?: string;
  nextActionDate: string;
  promiseAmount?: number;
  promiseDate: string;
  notes?: string;
  metadata?: string;
  scheduledFor: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CollectionPaymentPlan {
  id: string;
  tenantId: string;
  caseId?: string;
  totalAmount?: number;
  installmentAmount?: number;
  installmentCount?: number;
  completedInstallments?: number;
  status?: string;
  startDate: string;
  endDate: string;
  frequency?: string;
  nextPaymentDate: string;
  notes?: string;
  metadata?: string;
  completedAt: string;
  defaultedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CommandBoard {
  id: string;
  tenantId: string;
  eventId?: string;
  name?: string;
  description?: string;
  status?: string;
  isTemplate?: boolean;
  tags?: unknown[];
  autoPopulate?: boolean;
  scope?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CommandBoardCard {
  id: string;
  tenantId: string;
  boardId: string;
  title?: string;
  content?: string;
  cardType?: string;
  status?: string;
  positionX?: number;
  positionY?: number;
  width?: number;
  height?: number;
  zIndex?: number;
  color?: string;
  metadata?: string;
  groupId?: string;
  entityId?: string;
  entityType?: string;
  version?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CommandBoardGroup {
  id: string;
  tenantId: string;
  boardId: string;
  name?: string;
  color?: string;
  collapsed?: boolean;
  positionX?: number;
  positionY?: number;
  width?: number;
  height?: number;
  zIndex?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CommandBoardConnection {
  id: string;
  tenantId: string;
  boardId: string;
  fromCardId: string;
  toCardId: string;
  relationshipType?: string;
  label?: string;
  visible?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CommandBoardLayout {
  id: string;
  tenantId: string;
  boardId: string;
  userId: string;
  name?: string;
  viewport?: string;
  visibleCards?: string;
  gridSize?: number;
  showGrid?: boolean;
  snapToGrid?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Container {
  id: string;
  tenantId: string;
  name: string;
  containerType: string;
  locationId?: string;
  sizeDescription?: string;
  capacityVolumeMl?: number;
  capacityWeightG?: number;
  capacityPortions?: number;
  isReusable?: boolean;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProposalTemplate {
  id: string;
  tenantId: string;
  name?: string;
  description?: string;
  eventType?: string;
  defaultTerms?: string;
  defaultTaxRate?: number;
  defaultNotes?: string;
  defaultLineItems?: string;
  isActive?: boolean;
  isDefault?: boolean;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  fontFamily?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface InteractionAttachment {
  id: string;
  tenantId: string;
  clientInteractionId?: string;
  fileName?: string;
  fileUrl?: string;
  fileType?: string;
  fileSizeBytes?: number;
  uploadedBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CrmScoringRule {
  id: string;
  tenantId: string;
  ruleName?: string;
  field?: string;
  condition?: string;
  value?: string;
  points?: number;
  isActive?: boolean;
  priority?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Report {
  id: string;
  tenantId: string;
  name?: string;
  reportType?: string;
  queryConfig?: string;
  displayConfig?: string;
  isShared?: boolean;
  createdBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: string;
  tenantId: string;
  name?: string;
  documentType?: string;
  fileUrl?: string;
  fileSizeBytes?: number;
  status?: string;
  entityType?: string;
  entityId?: string;
  uploadedBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface AdminChatThread {
  id: string;
  tenantId: string;
  threadType?: string;
  slug?: string;
  directKey?: string;
  status?: string;
  createdBy?: string;
  lastMessageAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface AdminChatMessage {
  id: string;
  tenantId: string;
  threadId?: string;
  authorId?: string;
  authorName?: string;
  text?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CycleCountSession {
  id: string;
  tenantId: string;
  locationId: string;
  sessionId: string;
  sessionName: string;
  countType?: string;
  scheduledDate: string;
  startedAt: string;
  completedAt: string;
  finalizedAt: string;
  status?: string;
  totalItems?: number;
  countedItems?: number;
  totalVariance?: number;
  variancePercentage?: number;
  notes?: string;
  createdById?: string;
  approvedById?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface CycleCountRecord {
  id: string;
  tenantId: string;
  sessionId: string;
  itemId: string;
  itemNumber: string;
  itemName: string;
  storageLocationId: string;
  expectedQuantity?: number;
  countedQuantity?: number;
  variance?: number;
  variancePct?: number;
  countDate: string;
  countedById?: string;
  barcode?: string;
  notes?: string;
  isVerified?: boolean;
  verifiedById?: string;
  verifiedAt: string;
  syncStatus?: string;
  offlineId?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface VarianceReport {
  id: string;
  tenantId: string;
  sessionId: string;
  reportType: string;
  itemId: string;
  itemNumber: string;
  itemName: string;
  expectedQuantity?: number;
  countedQuantity?: number;
  variance?: number;
  variancePct?: number;
  accuracyScore?: number;
  status?: string;
  adjustmentType?: string;
  adjustmentAmount?: number;
  adjustmentDate: string;
  rejectedAt: string;
  rejectedBy?: string;
  rejectionReason?: string;
  notes?: string;
  rootCause?: string;
  resolutionNotes?: string;
  resolvedById?: string;
  resolvedAt: string;
  generatedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Deal {
  id: string;
  tenantId: string;
  leadId: string;
  title: string;
  value?: number;
  currency?: string;
  stage?: string;
  status?: string;
  probability?: number;
  expectedCloseDate: string;
  actualCloseDate: string;
  assignedTo?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Dish {
  id: string;
  tenantId: string;
  recipeId: string;
  name: string;
  description?: string;
  category?: string;
  serviceStyle?: string;
  defaultContainerId?: string;
  presentationImageUrl?: string;
  minPrepLeadDays?: number;
  maxPrepLeadDays?: number;
  portionSizeDescription?: string;
  dietaryTags?: string;
  allergens?: string;
  pricePerPerson?: number;
  costPerPerson?: number;
  isActive?: boolean;
  isSeasonal?: boolean;
  seasonLabel?: string;
  seasonStartMonth?: number;
  seasonEndMonth?: number;
  isEightySix?: boolean;
  eightySixReason?: string;
  eightySixAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface DocumentVersion {
  id: string;
  tenantId: string;
  documentId: string;
  versionNumber: number;
  content: string;
  changeDescription?: string;
  createdBy?: string;
  status?: string;
  approvedBy?: string;
  publishedBy?: string;
  supersededBy?: string;
  approvedAt: string;
  publishedAt: string;
  supersededAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmailTemplate {
  id: string;
  tenantId: string;
  name?: string;
  templateType?: string;
  subject?: string;
  body?: string;
  mergeFields?: string;
  isActive?: boolean;
  isDefault?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmailWorkflow {
  id: string;
  tenantId: string;
  name?: string;
  triggerType?: string;
  triggerConfig?: string;
  emailTemplateId?: string;
  emailTemplateTenantId?: string;
  recipientConfig?: string;
  isActive?: boolean;
  lastTriggeredAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmployeeAvailability {
  id: string;
  tenantId: string;
  employeeId?: string;
  dayOfWeek?: number;
  startTime?: string;
  endTime?: string;
  isAvailable?: boolean;
  effectiveFrom?: string;
  effectiveUntil?: string;
  isSuspended?: boolean;
  suspendReason?: string;
  suspendedAt: string;
  reinstatedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmployeeCertification {
  id: string;
  tenantId: string;
  employeeId?: string;
  certificationType?: string;
  certificationName?: string;
  issuedDate?: string;
  expiryDate?: string;
  documentUrl?: string;
  status?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Equipment {
  id: string;
  tenantId: string;
  locationId: string;
  name: string;
  type?: string;
  status?: string;
  serialNumber?: string;
  manufacturer?: string;
  model?: string;
  purchaseDate: string;
  warrantyExpiry: string;
  lastMaintenanceDate: string;
  nextMaintenanceDate: string;
  maintenanceIntervalDays?: number;
  usageHours?: number;
  maxUsageHours?: number;
  condition?: string;
  notes?: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface MaintenanceWorkOrder {
  id: string;
  tenantId: string;
  workOrderNumber?: string;
  areaId?: string;
  equipmentId?: string;
  equipmentName?: string;
  title: string;
  type?: string;
  priority?: string;
  status?: string;
  description?: string;
  reportedBy?: string;
  assignedTo?: string;
  scheduledDate: string;
  completedDate: string;
  estimatedCost?: number;
  actualCost?: number;
  partsUsed?: string;
  vendorId?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AutomatedFollowup {
  id: string;
  tenantId: string;
  eventId: string;
  type?: string;
  status?: string;
  scheduledDate: string;
  sentDate: string;
  recipientId?: string;
  subject?: string;
  body?: string;
  templateId?: string;
  errorMessage?: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventTimelineItem {
  id: string;
  tenantId: string;
  eventId: string;
  title: string;
  description?: string;
  itemType?: string;
  status?: string;
  assignedTo?: string;
  dueDate: string;
  completedAt: string;
  sortOrder?: number;
  createdAt: string;
  updatedAt: string;
}

export interface EventWaitlistEntry {
  id: string;
  tenantId: string;
  eventId: string;
  guestName: string;
  email?: string;
  phone?: string;
  partySize?: number;
  status?: string;
  notes?: string;
  joinedAt: string;
  notifiedAt: string;
  seatedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventBudget {
  id: string;
  tenantId: string;
  eventId: string;
  version?: number;
  status?: string;
  totalBudgetAmount?: number;
  totalActualAmount?: number;
  varianceAmount?: number;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BudgetLineItem {
  id: string;
  tenantId: string;
  budgetId: string;
  category: string;
  name: string;
  description?: string;
  budgetedAmount?: number;
  actualAmount?: number;
  varianceAmount?: number;
  sortOrder?: number;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventContract {
  id: string;
  tenantId: string;
  eventId: string;
  clientId: string;
  contractNumber?: string;
  title?: string;
  status?: string;
  documentUrl?: string;
  documentType?: string;
  notes?: string;
  expiresAt: string;
  sentAt: string;
  viewedAt: string;
  signedAt: string;
  canceledBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ContractSignature {
  id: string;
  tenantId: string;
  contractId: string;
  signedAt: string;
  signatureData?: string;
  signerName?: string;
  signerEmail?: string;
  signerRole?: string;
  ipAddress?: string;
  verifiedAt: string;
  invalidatedAt: string;
  invalidationReason?: string;
  isValid?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventDish {
  id: string;
  tenantId: string;
  eventId: string;
  dishId: string;
  quantity?: number;
  notes?: string;
  courseLabel?: string;
  sortOrder?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventGuest {
  id: string;
  tenantId: string;
  eventId?: string;
  guestName?: string;
  guestEmail?: string;
  guestPhone?: string;
  isPrimaryContact?: boolean;
  dietaryRestrictions?: string;
  allergenRestrictions?: string;
  notes?: string;
  declineReason?: string;
  specialMealRequired?: boolean;
  specialMealNotes?: string;
  tableAssignment?: string;
  mealPreference?: string;
  rsvpStatus?: string;
  rsvpAt: string;
  checkedInAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventImportWorkflow {
  id: string;
  tenantId: string;
  eventId?: string;
  idempotencyKey?: string;
  status?: string;
  currentStep?: number;
  totalSteps?: number;
  inputData?: string;
  outputData?: string;
  stepResults?: string;
  errors?: string;
  warnings?: string;
  confidence?: number;
  startedAt: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventReport {
  id: string;
  tenantId: string;
  eventId: string;
  name: string;
  version?: string;
  status?: string;
  completion?: number;
  checklistData?: string;
  parsedEventData?: string;
  reportConfig?: string;
  autoFillScore?: number;
  reviewNotes?: string;
  reviewedBy?: string;
  reviewedAt: string;
  completedAt: string;
  rejectedAt: string;
  rejectedBy?: string;
  rejectionReason?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Event {
  id: string;
  tenantId: string;
  clientId?: string;
  eventNumber?: string;
  title?: string;
  eventType?: string;
  eventDate: string;
  guestCount?: number;
  status?: string;
  budget?: number;
  ticketPrice?: number;
  ticketTier?: string;
  eventFormat?: string;
  accessibilityOptions: unknown[];
  featuredMediaUrl?: string;
  locationId?: string;
  venueId?: string;
  venueEntityId?: string;
  assignedTo?: string;
  venueName?: string;
  venueAddress?: string;
  notes?: string;
  tags: unknown[];
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventProfitability {
  id: string;
  tenantId: string;
  eventId: string;
  budgetedRevenue?: number;
  budgetedFoodCost?: number;
  budgetedLaborCost?: number;
  budgetedOverhead?: number;
  budgetedTotalCost?: number;
  budgetedGrossMargin?: number;
  actualRevenue?: number;
  actualFoodCost?: number;
  actualLaborCost?: number;
  actualOverhead?: number;
  actualTotalCost?: number;
  actualGrossMargin?: number;
  revenueVariance?: number;
  foodCostVariance?: number;
  laborCostVariance?: number;
  totalCostVariance?: number;
  marginVariancePct?: number;
  calculatedAt: string;
  calculationMethod?: string;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventSummary {
  id: string;
  tenantId: string;
  eventId: string;
  highlights?: string;
  issues?: string;
  financialPerformance?: string;
  clientFeedback?: string;
  insights?: string;
  overallSummary?: string;
  generatedAt: string;
  generationDurationMs?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventStaff {
  id: string;
  tenantId: string;
  eventId: string;
  staffMemberId: string;
  role?: string;
  notes?: string;
  shiftStart: string;
  shiftEnd: string;
  status?: string;
  confirmedAt: string;
  checkedInAt: string;
  checkedOutAt: string;
  noShowReason?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Venue {
  id: string;
  tenantId: string;
  name?: string;
  venueType?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  stateProvince?: string;
  postalCode?: string;
  countryCode?: string;
  capacity?: number;
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
  accessNotes?: string;
  cateringNotes?: string;
  layoutImageUrl?: string;
  tags: unknown[];
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventTimeline {
  id: string;
  tenantId: string;
  eventId: string;
  title?: string;
  scheduledAt: string;
  durationMinutes?: number;
  notes?: string;
  sortOrder?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TimelineTask {
  id: string;
  tenantId: string;
  eventId: string;
  title?: string;
  dueAt: string;
  status?: string;
  assignedTo?: string;
  notes?: string;
  sortOrder?: number;
  completedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventImport {
  id: string;
  tenantId: string;
  source?: string;
  fileName?: string;
  status?: string;
  totalRows?: number;
  importedRows?: number;
  skippedRows?: number;
  errorMessage?: string;
  completedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EventFollowup {
  id: string;
  tenantId: string;
  eventId: string;
  type?: string;
  dueAt: string;
  status?: string;
  assignedTo?: string;
  notes?: string;
  completedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BoardProjection {
  id: string;
  tenantId: string;
  boardId: string;
  entityType?: string;
  entityId?: string;
  positionX?: number;
  positionY?: number;
  width?: number;
  height?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BoardAnnotation {
  id: string;
  tenantId: string;
  boardId: string;
  text?: string;
  positionX?: number;
  positionY?: number;
  color?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Note {
  id: string;
  tenantId: string;
  title?: string;
  content?: string;
  color?: string;
  tags?: unknown[];
  entityType?: string;
  entityId?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Facility {
  id: string;
  tenantId: string;
  name: string;
  code?: string;
  facilityType?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  country?: string;
  phone?: string;
  status?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface FacilityArea {
  id: string;
  tenantId: string;
  venueId?: string;
  name: string;
  code?: string;
  areaType?: string;
  floor?: string;
  description?: string;
  squareFeet?: number;
  status?: string;
  createdAt: string;
  updatedAt: string;
}

export interface FacilityAsset {
  id: string;
  tenantId: string;
  facilityId?: string;
  areaId?: string;
  name: string;
  assetType?: string;
  assetClass?: string;
  status?: string;
  purchaseDate: string;
  purchasePrice?: number;
  currentValue?: number;
  depreciationRate?: number;
  serialNumber?: string;
  manufacturer?: string;
  model?: string;
  warrantyExpiry: string;
  lastMaintenanceAt: string;
  nextMaintenanceAt: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface FacilitySchedule {
  id: string;
  tenantId: string;
  facilityId?: string;
  areaId?: string;
  title: string;
  description?: string;
  scheduleType?: string;
  status?: string;
  startDate: string;
  endDate: string;
  assignedTo?: string;
  completedAt: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface FacilityWorkOrder {
  id: string;
  tenantId: string;
  facilityId?: string;
  areaId?: string;
  assetId?: string;
  title: string;
  description?: string;
  priority?: string;
  status?: string;
  category?: string;
  requestedBy?: string;
  assignedTo?: string;
  estimatedCost?: number;
  actualCost?: number;
  scheduledDate: string;
  completedDate: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Ingredient {
  id: string;
  tenantId: string;
  name: string;
  category?: string;
  defaultUnitId?: number;
  densityGPerMl?: number;
  shelfLifeDays?: number;
  storageInstructions?: string;
  allergens?: string;
  isActive?: boolean;
  inventoryItemId?: string;
  currentLotNumber?: string;
  currentLotReceivedAt: string;
  currentLotExpiresAt: string;
  isRecalled?: boolean;
  recallReason?: string;
  recalledAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface StorageLocation {
  id: string;
  tenantId: string;
  locationId: string;
  name: string;
  storageType: string;
  temperatureZone?: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryStock {
  id: string;
  tenantId: string;
  inventoryItemId: string;
  storageLocationId: string;
  quantityOnHand?: number;
  unitId: string;
  lastCountedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryAlert {
  id: string;
  tenantId: string;
  inventoryItemId: string;
  alertType: string;
  severity: string;
  message: string;
  status?: string;
  triggeredAt: string;
  acknowledgedAt: string;
  resolvedAt: string;
  acknowledgedBy?: string;
  resolvedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryForecast {
  id: string;
  tenantId: string;
  inventoryItemId: string;
  forecastDate: string;
  projectedQuantity?: number;
  confidence?: number;
  status?: string;
  publishedAt: string;
  approvedAt: string;
  approvedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ForecastInput {
  id: string;
  tenantId: string;
  inventoryItemId: string;
  inputDate: string;
  actualUsage?: number;
  source: string;
  createdAt: string;
  updatedAt: string;
}

export interface ReorderSuggestion {
  id: string;
  tenantId: string;
  inventoryItemId: string;
  suggestedQuantity?: number;
  reason: string;
  status?: string;
  createdAt: string;
  updatedAt: string;
}

export interface VendorContact {
  id: string;
  tenantId: string;
  inventorySupplierId: string;
  name: string;
  email?: string;
  phone?: string;
  role?: string;
  isPrimary?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface VendorRating {
  id: string;
  tenantId: string;
  inventorySupplierId: string;
  category: string;
  score?: number;
  comment?: string;
  ratedAt: string;
  ratedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryTransferItem {
  id: string;
  tenantId: string;
  inventoryTransferId: string;
  inventoryItemId: string;
  quantity?: number;
  unitId: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProcurementBudget {
  id: string;
  tenantId: string;
  name: string;
  periodStart: string;
  periodEnd: string;
  budgetAmount?: number;
  spentAmount?: number;
  status?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProcurementBudgetAlert {
  id: string;
  tenantId: string;
  procurementBudgetId: string;
  thresholdPct?: number;
  message: string;
  triggeredAt: string;
  acknowledgedAt: string;
  acknowledgedBy?: string;
  isAcknowledged?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AuditSchedule {
  id: string;
  tenantId: string;
  name: string;
  frequency: string;
  nextRunAt: string;
  lastRunAt: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryItem {
  id: string;
  tenantId: string;
  item_number: string;
  name: string;
  description?: string;
  category: string;
  unitOfMeasure?: string;
  unitCost?: number;
  quantityOnHand?: number;
  quantityReserved?: number;
  parLevel?: number;
  reorder_level?: number;
  supplierId?: string;
  tags?: string;
  fsa_status?: string;
  fsa_temp_logged?: boolean;
  fsa_allergen_info?: boolean;
  fsa_traceable?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface InventorySupplier {
  id: string;
  tenantId: string;
  name: string;
  supplierNumber?: string;
  contactPerson?: string;
  email?: string;
  phone?: string;
  paymentTerms?: string;
  notes?: string;
  tags?: string;
  isActive?: boolean;
  openPOCount?: number;
  approvedAt: string;
  approvedBy?: string;
  suspendedAt: string;
  suspendedReason?: string;
  blacklistedAt: string;
  blacklistedReason?: string;
  qualificationStatus?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryTransaction {
  id: string;
  tenantId: string;
  itemId: string;
  transactionType: string;
  quantity?: number;
  unitCost?: number;
  totalCost?: number;
  reference?: string;
  referenceType?: string;
  referenceId?: string;
  notes?: string;
  reason?: string;
  employeeId?: string;
  storageLocationId?: string;
  transactionDate: string;
  reversedAt: string;
  reversedBy?: string;
  reverseOfTransactionId?: string;
  isReversed?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface InventoryTransfer {
  id: string;
  tenantId: string;
  fromLocationId?: string;
  toLocationId?: string;
  status?: string;
  requestedBy?: string;
  approvedBy?: string;
  shippedBy?: string;
  receivedBy?: string;
  shipDate: string;
  receiveDate: string;
  discrepancyNotes?: string;
  hasDiscrepancy?: boolean;
  notes?: string;
  items?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Invoice {
  id: string;
  tenantId: string;
  invoiceNumber?: string;
  type?: string;
  status?: string;
  clientId?: string;
  eventId?: string;
  subtotal?: number;
  taxAmount?: number;
  discountAmount?: number;
  total?: number;
  amountPaid?: number;
  amountDue?: number;
  paymentTerms?: number;
  dueDate: string;
  paidAt: string;
  depositPercentage?: number;
  depositRequired?: number;
  depositPaid?: number;
  issuedAt: string;
  sentAt: string;
  viewedAt: string;
  overdueSince: string;
  reminderCount?: number;
  lastReminderAt: string;
  quickBooksId?: string;
  goodshuffleId?: string;
  externalSyncStatus?: string;
  notes?: string;
  internalNotes?: string;
  lineItems?: string;
  metadata?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TemperatureProbe {
  id: string;
  tenantId: string;
  name: string;
  equipmentId: string;
  location: string;
  minThreshold: number;
  maxThreshold: number;
  isActive?: boolean;
  lastCalibratedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TemperatureLog {
  id: string;
  tenantId: string;
  equipmentId: string;
  recordedBy: string;
  temperature: number;
  recordedAt: string;
  withinRange: boolean;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TemperatureReading {
  id: string;
  tenantId: string;
  probeId: string;
  temperature: number;
  recordedAt: string;
  withinRange: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface IotAlertRule {
  id: string;
  tenantId: string;
  name: string;
  equipmentId: string;
  metric: string;
  sensorType: string;
  condition: string;
  threshold: number;
  thresholdMin?: number;
  thresholdMax?: number;
  comparison: string;
  severity: string;
  durationMs?: number;
  alertAction?: string;
  isActive?: boolean;
  notifyRoles?: string;
  notifyChannels?: string;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IoTAlert {
  id: string;
  tenantId: string;
  probeId: string;
  ruleId?: string;
  severity: string;
  message: string;
  value: number;
  status?: string;
  triggeredAt: string;
  alertNumber?: string;
  alertType?: string;
  title?: string;
  temperature?: number;
  acknowledgedBy?: string;
  resolvedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CorrectiveAction {
  id: string;
  tenantId: string;
  sourceType: string;
  sourceId: string;
  description: string;
  assignedTo?: string;
  status?: string;
  dueAt: string;
  resolvedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface QualityCheck {
  id: string;
  tenantId: string;
  checkType: string;
  performedBy: string;
  status?: string;
  performedAt: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface QualityCheckItem {
  id: string;
  tenantId: string;
  qualityCheckId: string;
  criterion: string;
  passed?: boolean;
  notes?: string;
  sortOrder?: number;
  createdAt: string;
  updatedAt: string;
}

export interface KitchenTaskClaim {
  id: string;
  tenantId: string;
  kitchenTaskId: string;
  employeeId: string;
  claimedAt: string;
  status?: string;
  releasedAt: string;
  releaseReason?: string;
  createdAt: string;
  updatedAt: string;
}

export interface KitchenTaskProgress {
  id: string;
  tenantId: string;
  kitchenTaskId: string;
  employeeId: string;
  status: string;
  progressPct: number;
  note?: string;
  recordedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TaskBundle {
  id: string;
  tenantId: string;
  name: string;
  eventId?: string;
  description?: string;
  status?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TaskBundleItem {
  id: string;
  tenantId: string;
  taskBundleId: string;
  kitchenTaskId: string;
  sortOrder?: number;
  createdAt: string;
  updatedAt: string;
}

export interface BulkCombineRule {
  id: string;
  tenantId: string;
  name: string;
  matchCriteria: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface MethodVideo {
  id: string;
  tenantId: string;
  prepMethodId: string;
  title: string;
  url: string;
  durationSeconds?: number;
  createdAt: string;
  updatedAt: string;
}

export interface PrepListImport {
  id: string;
  tenantId: string;
  source: string;
  fileName: string;
  status?: string;
  importedAt: string;
  errorMessage?: string;
  createdAt: string;
  updatedAt: string;
}

export interface KitchenTask {
  id: string;
  tenantId: string;
  title: string;
  summary: string;
  status?: string;
  priority?: number;
  complexity?: number;
  tags?: string;
  assignedTo?: string;
  dueDate: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface KnowledgeBaseEntry {
  id: string;
  tenantId: string;
  title: string;
  category?: string;
  content?: string;
  tags?: string;
  status?: string;
  authorId?: string;
  publishedAt: string;
  viewCount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface LaborBudget {
  id: string;
  tenantId: string;
  locationId?: string;
  periodStart?: string;
  periodEnd?: string;
  budgetAmount?: number;
  actualAmount?: number;
  budgetType?: string;
  status?: string;
  notes?: string;
  createdBy?: string;
  approvedBy?: string;
  approvedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BudgetAlert {
  id: string;
  tenantId: string;
  budgetId?: string;
  alertType?: string;
  thresholdPct?: number;
  actualPct?: number;
  message?: string;
  isAcknowledged?: boolean;
  acknowledgedBy?: string;
  acknowledgedAt: string;
  resolved?: boolean;
  resolvedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Lead {
  id: string;
  tenantId: string;
  source?: string;
  companyName?: string;
  contactName?: string;
  contactEmail?: string;
  contactPhone?: string;
  eventType?: string;
  eventDate: string;
  estimatedGuests?: number;
  estimatedValue?: number;
  status?: string;
  assignedTo?: string;
  notes?: string;
  convertedToClientId?: string;
  convertedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Driver {
  id: string;
  tenantId: string;
  name: string;
  email?: string;
  phone?: string;
  licenseNumber?: string;
  licenseExpiry: string;
  vehicleId?: string;
  status?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Vehicle {
  id: string;
  tenantId: string;
  make: string;
  model: string;
  year?: number;
  plateNumber?: string;
  vin?: string;
  capacityWeight?: number;
  capacityVolume?: number;
  fuelType?: string;
  mileage?: number;
  status?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface LogisticsRoute {
  id: string;
  tenantId: string;
  name: string;
  status?: string;
  vehicleId?: string;
  driverId?: string;
  startLocation?: string;
  endLocation?: string;
  distance?: number;
  estimatedDuration?: number;
  scheduledStart: string;
  scheduledEnd: string;
  actualStart: string;
  actualEnd: string;
  stops?: number;
  completedStops?: number;
  delayMinutes?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface LogisticsDispatch {
  id: string;
  tenantId: string;
  routeId: string;
  driverId?: string;
  vehicleId?: string;
  status?: string;
  priority?: string;
  estimatedDeliveryTime: string;
  actualDeliveryTime: string;
  departedAt: string;
  failureReason?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Menu {
  id: string;
  tenantId: string;
  name: string;
  description?: string;
  category?: string;
  isActive?: boolean;
  basePrice?: number;
  pricePerPerson?: number;
  minGuests?: number;
  maxGuests?: number;
  isSeasonal?: boolean;
  seasonLabel?: string;
  seasonYear?: number;
  status?: string;
  publishedAt: string;
  archivedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface MenuDish {
  id: string;
  tenantId: string;
  menuId: string;
  dishId: string;
  course?: string;
  sortOrder?: number;
  isOptional?: boolean;
  priceOverride?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Notification {
  id: string;
  tenantId: string;
  recipientEmployeeId: string;
  notificationType?: string;
  title?: string;
  body?: string;
  actionUrl?: string;
  isRead?: boolean;
  readAt: string;
  correlationId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface OverrideAudit {
  id: string;
  tenantId: string;
  entityType?: string;
  entityId?: string;
  constraintId?: string;
  guardExpression?: string;
  overriddenBy?: string;
  overrideReason?: string;
  authorizedBy?: string;
  authorizedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaymentMethod {
  id: string;
  tenantId: string;
  clientId?: string;
  externalMethodId?: string;
  type?: string;
  cardLastFour?: string;
  cardNetwork?: string;
  cardExpiryMonth?: number;
  cardExpiryYear?: number;
  cardHolderName?: string;
  bankAccountLastFour?: string;
  bankAccountType?: string;
  bankRoutingNumber?: string;
  walletProvider?: string;
  walletEmail?: string;
  status?: string;
  isDefault?: boolean;
  fraudFlagged?: boolean;
  verifiedAt: string;
  verificationMethod?: string;
  nickname?: string;
  metadata?: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Payment {
  id: string;
  tenantId: string;
  amount?: number;
  currency?: string;
  status?: string;
  methodType?: string;
  invoiceId?: string;
  eventId?: string;
  clientId?: string;
  gatewayTransactionId?: string;
  gatewayPaymentMethodId?: string;
  processor?: string;
  processorResponseCode?: string;
  processorResponseMessage?: string;
  processedAt: string;
  completedAt: string;
  refundedAt: string;
  chargebackAt: string;
  fraudStatus?: string;
  fraudScore?: number;
  reviewedAt: string;
  reviewedBy?: string;
  description?: string;
  externalReference?: string;
  metadata?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PayrollPeriod {
  id: string;
  tenantId: string;
  periodStart?: string;
  periodEnd?: string;
  status?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface EmployeeDeduction {
  id: string;
  tenantId: string;
  employeeId?: string;
  type?: string;
  name?: string;
  amount?: number;
  percentage?: number;
  isPreTax?: boolean;
  effectiveDate?: string;
  endDate?: string;
  maxAnnualAmount?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PayrollApprovalHistory {
  id: string;
  tenantId: string;
  payrollRunId?: string;
  action?: string;
  previousStatus?: string;
  newStatus?: string;
  performedBy?: string;
  performedAt: string;
  reason?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PayrollRun {
  id: string;
  tenantId: string;
  payrollPeriodId?: string;
  runDate?: string;
  status?: string;
  totalGross?: number;
  totalDeductions?: number;
  totalNet?: number;
  approvedBy?: string;
  approvedAt: string;
  rejectedBy?: string;
  paidAt: string;
  rejectReason?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PrepComment {
  id: string;
  tenantId: string;
  taskId: string;
  employeeId: string;
  commentText: string;
  isResolved?: boolean;
  resolvedAt: string;
  resolvedBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PrepList {
  id: string;
  tenantId: string;
  eventId: string;
  name: string;
  batchMultiplier?: number;
  dietaryRestrictions?: string;
  status?: string;
  totalItems?: number;
  totalEstimatedTime?: number;
  notes?: string;
  generatedAt: string;
  finalizedAt: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface PrepListItem {
  id: string;
  tenantId: string;
  prepListId: string;
  stationId: string;
  stationName: string;
  ingredientId: string;
  ingredientName: string;
  category?: string;
  baseQuantity?: number;
  baseUnit?: string;
  scaledQuantity?: number;
  scaledUnit?: string;
  isOptional?: boolean;
  preparationNotes?: string;
  allergens?: string;
  dietarySubstitutions?: string;
  dishId?: string;
  dishName?: string;
  recipeVersionId?: string;
  sortOrder?: number;
  isCompleted?: boolean;
  completedAt: string;
  completedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PrepMethod {
  id: string;
  tenantId: string;
  name: string;
  category?: string;
  description?: string;
  estimatedDurationMinutes?: number;
  requiresCertification?: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PrepTaskPlanWorkflow {
  id: string;
  tenantId: string;
  eventId?: string;
  idempotencyKey?: string;
  status?: string;
  currentStep?: number;
  totalSteps?: number;
  generationOptions?: string;
  generatedTasks?: string;
  reviewedTasks?: string;
  approvedTaskIds?: string;
  rejectedTaskIds?: string;
  instantiatedTaskIds?: string;
  scheduledWindows?: string;
  constraintOutcomes?: string;
  errors?: string;
  warnings?: string;
  generatedCount?: number;
  approvedCount?: number;
  instantiatedCount?: number;
  reviewedBy?: string;
  reviewedAt: string;
  approvedBy?: string;
  approvedAt: string;
  startedAt: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PrepTask {
  id: string;
  tenantId: string;
  eventId: string;
  prepListId?: string;
  name: string;
  taskType?: string;
  status?: string;
  stationId?: string;
  claimedBy?: string;
  claimedAt: string;
  quantityTotal?: number;
  quantityCompleted?: number;
  quantityUnitId?: string;
  servingsTotal?: number;
  startByDate: string;
  dueByDate: string;
  priority?: number;
  dishId?: string;
  locationId?: string;
  estimatedMinutes?: number;
  dueByTime: string;
  notes?: string;
  ingredients?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PricingTier {
  id: string;
  tenantId: string;
  catalogEntryId: string;
  tierName?: string;
  minQuantity?: number;
  maxQuantity?: number;
  unitCost?: number;
  discountPercent?: number;
  effectiveFrom: string;
  effectiveTo: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseRequisition {
  id: string;
  tenantId: string;
  requisitionNumber: string;
  requestedBy?: string;
  requestDate: string;
  requiredBy: string;
  locationId?: string;
  department?: string;
  justification?: string;
  status?: string;
  subtotal?: number;
  estimatedTax?: number;
  estimatedShipping?: number;
  estimatedTotal?: number;
  approvedBy?: string;
  approvedAt: string;
  managerApprovalBy?: string;
  managerApprovalAt: string;
  financeApprovalBy?: string;
  financeApprovalAt: string;
  convertedToPoId?: string;
  convertedAt: string;
  rejectionReason?: string;
  notes?: string;
  submittedAt: string;
  itemCategory?: string;
  priority?: string;
  deletedAt: string;
  itemCount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseRequisitionItem {
  id: string;
  tenantId: string;
  requisitionId: string;
  itemId: string;
  itemName?: string;
  quantityRequested?: number;
  unitId?: number;
  estimatedUnitCost?: number;
  estimatedTotalCost?: number;
  suggestedVendorId?: string;
  suggestedVendorName?: string;
  specifications?: string;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Proposal {
  id: string;
  tenantId: string;
  proposalNumber?: string;
  clientId?: string;
  leadId?: string;
  eventId?: string;
  title?: string;
  eventDate: string;
  eventType?: string;
  guestCount?: number;
  venueName?: string;
  venueAddress?: string;
  subtotal?: number;
  taxRate?: number;
  taxAmount?: number;
  discountAmount?: number;
  total?: number;
  status?: string;
  validUntil: string;
  sentAt: string;
  viewedAt: string;
  acceptedAt: string;
  rejectedAt: string;
  notes?: string;
  termsAndConditions?: string;
  lineItemCount?: number;
  publicToken?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ProposalLineItem {
  id: string;
  tenantId: string;
  proposalId: string;
  itemType?: string;
  category?: string;
  description?: string;
  quantity?: number;
  unitOfMeasure?: string;
  unitPrice?: number;
  total?: number;
  totalPrice?: number;
  sortOrder?: number;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseOrder {
  id: string;
  tenantId: string;
  poNumber: string;
  vendorId: string;
  locationId: string;
  orderDate: string;
  expectedDeliveryDate: string;
  actualDeliveryDate: string;
  status?: string;
  subtotal?: number;
  taxAmount?: number;
  shippingAmount?: number;
  total?: number;
  notes?: string;
  submittedBy?: string;
  submittedAt: string;
  receivedBy?: string;
  receivedAt: string;
  deletedAt: string;
  itemCount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseOrderItem {
  id: string;
  tenantId: string;
  purchaseOrderId: string;
  itemId: string;
  quantityOrdered?: number;
  quantityReceived?: number;
  unitId?: number;
  unitCost?: number;
  totalCost?: number;
  qualityStatus?: string;
  discrepancyType?: string;
  discrepancyAmount?: number;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface QACheck {
  id: string;
  tenantId: string;
  location?: string;
  checkType: string;
  result?: string;
  status?: string;
  inspector?: string;
  notes?: string;
  completedAt: string;
  reinspectedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface QACorrectiveAction {
  id: string;
  tenantId: string;
  checkId: string;
  description: string;
  assignedTo?: string;
  priority?: string;
  status?: string;
  resolutionNotes?: string;
  escalatedTo?: string;
  escalationReason?: string;
  dueDate: string;
  resolvedAt: string;
  escalatedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface QATemperatureLog {
  id: string;
  tenantId: string;
  location: string;
  temperature: number;
  unit?: string;
  equipment?: string;
  recordedBy?: string;
  notes?: string;
  loggedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface RateLimitConfig {
  id: string;
  tenantId: string;
  name?: string;
  endpointPattern?: string;
  windowMs?: number;
  maxRequests?: number;
  burstAllowance?: number;
  priority?: number;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Recipe {
  id: string;
  tenantId: string;
  name: string;
  category?: string;
  cuisineType?: string;
  description?: string;
  tags: unknown[];
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface RecipeVersion {
  id: string;
  recipeId: string;
  tenantId: string;
  name: string;
  versionNumber: number;
  category?: string;
  cuisineType?: string;
  description?: string;
  tags?: string;
  yieldQuantity?: number;
  yieldUnitId?: number;
  yieldDescription?: string;
  prepTimeMinutes?: number;
  cookTimeMinutes?: number;
  restTimeMinutes?: number;
  difficultyLevel?: number;
  instructions?: string;
  notes?: string;
  ingredientCount?: number;
  stepCount?: number;
  totalCost?: number;
  costPerYield?: number;
  status?: string;
  publishedAt: string;
  approvedAt: string;
  approvedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface RecipeIngredient {
  id: string;
  tenantId: string;
  recipeVersionId: string;
  ingredientId: string;
  quantity: number;
  unitId: number;
  sortOrder: number;
  preparationNotes?: string;
  isOptional?: boolean;
  wasteFactor?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface RecipeStep {
  id: string;
  tenantId: string;
  recipeVersionId: string;
  stepNumber: number;
  instruction: string;
  durationMinutes?: number;
  temperatureValue?: number;
  temperatureUnit?: string;
  equipmentNeeded?: string;
  tips?: string;
  videoUrl?: string;
  imageUrl?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface RevenueRecognitionSchedule {
  id: string;
  tenantId: string;
  invoiceId: string;
  eventId: string;
  contractId: string;
  clientId: string;
  totalAmount?: number;
  recognizedAmount?: number;
  remainingAmount?: number;
  method?: string;
  status?: string;
  startDate: string;
  endDate: string;
  recognitionPeriod?: number;
  serviceStartDate: string;
  serviceEndDate: string;
  totalMilestones?: number;
  completedMilestones?: number;
  description?: string;
  notes?: string;
  metadata?: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface RevenueRecognitionLine {
  id: string;
  tenantId: string;
  scheduleId: string;
  sequence?: number;
  amount?: number;
  recognizedAmount?: number;
  status?: string;
  dueDate: string;
  recognizedAt: string;
  milestoneId?: string;
  milestoneName?: string;
  milestoneDescription?: string;
  description?: string;
  notes?: string;
  metadata?: string;
  createdAt: string;
  updatedAt: string;
}

export interface RolePolicy {
  id: string;
  tenantId: string;
  roleId: string;
  roleName?: string;
  permissions?: unknown[];
  description?: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface SampleData {
  id: string;
  tenantId: string;
  seededAt: string;
  clearedAt: string;
  isSeeded?: boolean;
  eventsCreated?: number;
  clientsCreated?: number;
  usersCreated?: number;
  recipesCreated?: number;
  createdAt: string;
  updatedAt: string;
}

export interface Schedule {
  id: string;
  tenantId: string;
  locationId?: string;
  scheduleDate: string;
  status?: string;
  publishedAt: string;
  publishedBy?: string;
  approvedBy?: string;
  approvedAt: string;
  notes?: string;
  shiftCount?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ScheduleShift {
  id: string;
  tenantId: string;
  scheduleId: string;
  employeeId: string;
  locationId: string;
  shiftStart?: string;
  shiftEnd?: string;
  roleDuringShift?: string;
  notes?: string;
  swapOfferedTo?: string;
  swapStatus?: string;
  swapOfferedAt: string;
  swapAcceptedAt: string;
  inheritedContext?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Shipment {
  id: string;
  tenantId: string;
  shipmentNumber: string;
  status?: string;
  purchaseOrderId?: string;
  eventId?: string;
  supplierId?: string;
  locationId?: string;
  scheduledDate: string;
  shippedDate: string;
  estimatedDeliveryDate: string;
  actualDeliveryDate: string;
  totalItems?: number;
  shippingCost?: number;
  totalValue?: number;
  trackingNumber?: string;
  carrier?: string;
  shippingMethod?: string;
  deliveredBy?: string;
  receivedBy?: string;
  signatureData?: string;
  notes?: string;
  internalNotes?: string;
  reference?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ShipmentItem {
  id: string;
  tenantId: string;
  shipmentId: string;
  itemId: string;
  quantityShipped?: number;
  quantityReceived?: number;
  quantityDamaged?: number;
  unitId?: number;
  unitCost?: number;
  totalCost?: number;
  condition?: string;
  conditionNotes?: string;
  lotNumber?: string;
  expirationDate: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface SmsAutomationRule {
  id: string;
  tenantId: string;
  name?: string;
  description?: string;
  triggerType?: string;
  triggerConfig?: string;
  templateId?: string;
  customMessage?: string;
  recipientType?: string;
  recipientConfig?: string;
  isActive?: boolean;
  priority?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TimecardApproval {
  id: string;
  tenantId: string;
  employeeId: string;
  payrollPeriodId: string;
  status?: string;
  approvedBy?: string;
  approvedAt: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PayrollLineItem {
  id: string;
  tenantId: string;
  payrollRunId: string;
  employeeId: string;
  grossPay?: number;
  netPay?: number;
  totalDeductions?: number;
  hoursWorked?: number;
  hoursRegular?: number;
  hoursOvertime?: number;
  rateRegular?: number;
  rateOvertime?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TipPool {
  id: string;
  tenantId: string;
  periodStart: string;
  periodEnd: string;
  periodId?: string;
  eventId?: string;
  totalTips?: number;
  status?: string;
  allocationRule?: string;
  fixedShares?: string;
  distributedAmount?: number;
  distributedAt: string;
  distributedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DisciplinaryAction {
  id: string;
  tenantId: string;
  employeeId: string;
  actionType?: string;
  reason?: string;
  severity?: string;
  status?: string;
  issuedBy?: string;
  escalatedTo?: string;
  escalationReason?: string;
  escalatedAt: string;
  issuedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface ActionMilestone {
  id: string;
  tenantId: string;
  disciplinaryActionId: string;
  title?: string;
  dueAt: string;
  status?: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PerformanceReview {
  id: string;
  tenantId: string;
  employeeId: string;
  reviewerId: string;
  reviewPeriod?: string;
  overallRating?: number;
  status?: string;
  submittedAt: string;
  signedOffAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TrainingCompletion {
  id: string;
  tenantId: string;
  employeeId: string;
  trainingModuleId: string;
  completedAt: string;
  score?: number;
  passed?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface OnboardingTask {
  id: string;
  tenantId: string;
  title?: string;
  description?: string;
  sortOrder?: number;
  isRequired?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface OnboardingCompletion {
  id: string;
  tenantId: string;
  employeeId: string;
  onboardingTaskId: string;
  completedAt: string;
  status?: string;
  createdAt: string;
  updatedAt: string;
}

export interface OpenShift {
  id: string;
  tenantId: string;
  scheduleId: string;
  role?: string;
  shiftStart: string;
  shiftEnd: string;
  status?: string;
  claimedBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DeliveryRoute {
  id: string;
  tenantId: string;
  name?: string;
  driverId?: string;
  routeDate: string;
  status?: string;
  totalStops?: number;
  distanceMiles?: number;
  createdAt: string;
  updatedAt: string;
}

export interface RouteStop {
  id: string;
  tenantId: string;
  deliveryRouteId: string;
  eventId?: string;
  address?: string;
  sequence?: number;
  scheduledAt: string;
  status?: string;
  arrivedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaymentRefundAttempt {
  id: string;
  tenantId: string;
  paymentId: string;
  amount?: number;
  reason?: string;
  status?: string;
  attemptedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PreventiveMaintenanceSchedule {
  id: string;
  tenantId: string;
  scheduleNumber?: string;
  areaId?: string;
  equipmentId?: string;
  title?: string;
  description?: string;
  frequency?: string;
  intervalDays?: number;
  nextDueAt: string;
  lastCompletedAt: string;
  assignedTo?: string;
  estimatedHours?: number;
  estimatedCost?: number;
  status?: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface StaffMember {
  id: string;
  tenantId: string;
  displayName?: string;
  email?: string;
  phone?: string;
  role?: string;
  status?: string;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface StaffPerformance {
  id: string;
  tenantId: string;
  employeeId: string;
  reviewType?: string;
  status?: string;
  rating?: number;
  reviewerId?: string;
  periodStart: string;
  periodEnd: string;
  strengths?: string;
  improvements?: string;
  goals?: string;
  notes?: string;
  acknowledgementNotes?: string;
  completedAt: string;
  acknowledgedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Station {
  id: string;
  tenantId: string;
  locationId: string;
  name: string;
  stationType?: string;
  capacitySimultaneousTasks?: number;
  equipmentList?: string;
  isActive?: boolean;
  inMaintenance?: boolean;
  maintenanceReason?: string;
  maintenanceStartAt: string;
  currentTaskCount?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TimeEntry {
  id: string;
  tenantId: string;
  employeeId: string;
  locationId?: string;
  shiftId?: string;
  clockIn: string;
  clockOut: string;
  breakMinutes?: number;
  notes?: string;
  approvedBy?: string;
  approvedAt: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TimecardEditRequest {
  id: string;
  tenantId: string;
  timeEntryId: string;
  employeeId: string;
  requestedClockIn: string;
  requestedClockOut: string;
  requestedBreakMinutes?: number;
  reason: string;
  status?: string;
  createdAt: string;
  updatedAt: string;
}

export interface TimeOffRequest {
  id: string;
  tenantId: string;
  employeeId?: string;
  startDate?: string;
  endDate?: string;
  reason?: string;
  requestType?: string;
  status?: string;
  processedBy?: string;
  processedAt: string;
  rejectionReason?: string;
  balanceSnapshot?: number;
  balanceUnit?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TrainingModule {
  tenantId: string;
  id: string;
  code?: string;
  title?: string;
  description?: string;
  contentUrl?: string;
  contentType?: string;
  durationMinutes?: number;
  category?: string;
  isRequired?: boolean;
  passThresholdPercent?: number;
  maxAttempts?: number;
  requiredRole?: string;
  isActive?: boolean;
  status?: string;
  version?: number;
  publishedAt: string;
  archivedAt: string;
  notes?: string;
  createdBy?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TrainingQuestion {
  tenantId: string;
  id: string;
  moduleId: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  isActive?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface TrainingAssignment {
  tenantId: string;
  id: string;
  moduleId: string;
  moduleCode?: string;
  moduleTitle?: string;
  staffMemberId: string;
  staffRole?: string;
  status?: string;
  dueAt: string;
  dueDateReviewNeeded?: boolean;
  firstShiftAt: string;
  startedAt: string;
  completedAt: string;
  waivedAt: string;
  waiverReason?: string;
  waiverApprovedBy?: string;
  attemptCount?: number;
  lastAttemptId?: string;
  lastScorePercent?: number;
  passThresholdPercent?: number;
  maxAttempts?: number;
  managerReviewRequired?: boolean;
  reminderSentAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface TrainingAttempt {
  tenantId: string;
  id: string;
  assignmentId: string;
  moduleId: string;
  staffMemberId: string;
  attemptNumber?: number;
  scorePercent?: number;
  passThresholdPercent?: number;
  passed?: boolean;
  managerReviewRequired?: boolean;
  answersJson?: string;
  createdAt: string;
  updatedAt: string;
}

export interface StaffTrainingSignal {
  tenantId: string;
  id: string;
  staffMemberId: string;
  moduleId: string;
  assignmentId: string;
  signalType?: string;
  reason?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingModuleDefinition {
  tenantId: string;
  id: string;
  moduleId?: string;
  code?: string;
  title?: string;
  description?: string;
  contentType?: string;
  contentUrl?: string;
  durationMinutes?: number;
  category?: string;
  isRequired?: boolean;
  passThresholdPercent?: number;
  maxAttempts?: number;
  requiredRole?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion01Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion02Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion03Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion04Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion05Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion06Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion07Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion08Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion09Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SelOnboardingTrainingQuestion10Definition {
  tenantId: string;
  id: string;
  questionId?: string;
  moduleId?: string;
  code?: string;
  sectionTitle?: string;
  displayOrder?: number;
  prompt?: string;
  optionA?: string;
  optionB?: string;
  optionC?: string;
  optionD?: string;
  correctOptionKey?: string;
  explanation?: string;
  whyItMatters?: string;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  tenantId: string;
  email: string;
  firstName?: string;
  lastName?: string;
  role?: string;
  authUserId?: string;
  employeeNumber?: string;
  phone?: string;
  employmentType?: string;
  hourlyRate?: number;
  salaryAnnual?: number;
  hireDate: string;
  terminationDate: string;
  isActive?: boolean;
  avatarUrl?: string;
  roleId?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface VendorCatalog {
  id: string;
  tenantId: string;
  supplierId: string;
  itemNumber?: string;
  itemName?: string;
  description?: string;
  category?: string;
  baseUnitCost?: number;
  currency?: string;
  unitOfMeasure?: string;
  leadTimeDays?: number;
  leadTimeMinDays?: number;
  leadTimeMaxDays?: number;
  minimumOrderQuantity?: number;
  orderMultiple?: number;
  isActive?: boolean;
  effectiveFrom: string;
  effectiveTo: string;
  supplierSku?: string;
  notes?: string;
  tags: unknown[];
  lastCostUpdate: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface VendorContract {
  id: string;
  tenantId: string;
  contractNumber: string;
  vendorId: string;
  vendorName?: string;
  contractType?: string;
  status?: string;
  startDate: string;
  endDate: string;
  autoRenew?: boolean;
  renewalTermDays?: number;
  noticeDaysBeforeRenewal?: number;
  paymentTerms?: string;
  deliveryTerms?: string;
  minimumOrderQuantity?: number;
  annualSpendCommitment?: number;
  spendToPeriod?: number;
  currencyCode?: string;
  approvedBy?: string;
  approvedAt: string;
  terminatedBy?: string;
  terminatedAt: string;
  terminationReason?: string;
  contractUrl?: string;
  notes?: string;
  complianceScore?: number;
  lastComplianceReview: string;
  slaBreachCount?: number;
  onTimeDeliveryRate?: number;
  qualityRating?: number;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Vendor {
  id: string;
  tenantId: string;
  name: string;
  type?: string;
  status?: string;
  email?: string;
  phone?: string;
  website?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  taxId?: string;
  paymentTerms?: string;
  rating?: number;
  ratingCount?: number;
  notes?: string;
  approvedAt: string;
  approvedBy?: string;
  suspendedAt: string;
  suspendedReason?: string;
  blacklistedAt: string;
  blacklistedReason?: string;
  lastContactAddedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface VersionedEntity {
  id: string;
  tenantId: string;
  entityType: string;
  entityId: string;
  entityName: string;
  isLocked?: boolean;
  currentVersionId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface EntityVersion {
  id: string;
  tenantId: string;
  versionedEntityId: string;
  versionNumber: number;
  changeReason?: string;
  changeSummary?: string;
  changeType: string;
  snapshotData?: string;
  metadata?: string;
  isApproved?: boolean;
  approvedAt: string;
  approvedBy?: string;
  createdBy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface VersionApproval {
  id: string;
  tenantId: string;
  entityVersionId: string;
  approverId: string;
  status: string;
  comments?: string;
  reviewedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface WasteEntry {
  id: string;
  tenantId: string;
  inventoryItemId?: string;
  reasonId?: number;
  quantity?: number;
  unitId?: number;
  locationId?: string;
  eventId?: string;
  loggedBy?: string;
  loggedAt: string;
  approvedBy?: string;
  approvedAt: string;
  status?: string;
  unitCost?: number;
  totalCost?: number;
  notes?: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface WorkOrder {
  id: string;
  tenantId: string;
  equipmentId: string;
  equipmentName?: string;
  title: string;
  type?: string;
  priority?: string;
  status?: string;
  description?: string;
  scheduledDate: string;
  assignedTo?: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface Workflow {
  id: string;
  tenantId: string;
  name?: string;
  description?: string;
  triggerType?: string;
  triggerConfig?: string;
  isActive?: boolean;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface WorkforceOptimization {
  id: string;
  tenantId: string;
  locationId?: string;
  optimizationType?: string;
  status?: string;
  completedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface PerformancePrediction {
  id: string;
  tenantId: string;
  employeeId?: string;
  predictionType?: string;
  predictionHorizon?: number;
  predictionScore?: number;
  confidence?: string;
  factors?: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
