// @generated
// Generated by Capsule-Pro Manifest Generator v0.1.0
// DO NOT EDIT - Changes will be overwritten
// Source manifest: C:\projects\capsule-pro\packages\kitchen-ops\manifests\recipe-rules.manifest
// Generator: packages/manifest/src/generators/capsule-pro.ts
//
// Escape hatch: Create a manual route in a sibling directory and import
// the generated handler as a helper function.
//
// Provenance:
//   Generated At: 2026-02-09T17:30:19.724Z

import { auth } from "@repo/auth/server";
import { database } from "@repo/database";
import {
  manifestErrorResponse,
  manifestSuccessResponse,
} from "@repo/kitchen-ops/route-helpers";
import { getTenantIdForOrg } from "@/app/lib/tenant";

/**
 * Generated route handler for RecipeVersion
 *
 * Generated from: C:\projects\capsule-pro\packages\kitchen-ops\manifests\recipe-rules.manifest
 *
 * This handler uses the Manifest runtime for:
 * - Entity creation with constraint validation
 * - Command execution with guard checking
 * - Automatic persistence through PrismaStore
 */

export async function GET(_request: Request) {
  // 1. Auth check
  const { orgId } = await auth();
  if (!orgId) {
    return manifestErrorResponse(new Error("Unauthorized"), 401);
  }

  // 2. Tenant resolution
  const tenantId = await getTenantIdForOrg(orgId);

  // 3. Execute operation
  try {
    // Query RecipeVersion using Prisma (runtime is for commands, not queries)
    const recipeVersions = await database.recipeVersion.findMany({
      where: {
        tenantId,
        deletedAt: null,
      },
      orderBy: {
        createdAt: "desc",
      },
    });

    return manifestSuccessResponse({ recipeVersions });
  } catch (error) {
    return manifestErrorResponse(
      error instanceof Error ? error : new Error(String(error))
    );
  }
}
