/**
 * Inventory Test: Manifest Code Generation Surface Area
 *
 * This test tracks the SURFACE AREA of manual vs generated Manifest integration.
 * It is NOT a blocking test - it always passes.
 *
 * Purpose: Track migration progress from manual integration to code-generated routes.
 * Status: Pre-generator inventory - no Capsule-Pro projection exists yet.
 *
 * See: .specify/memory/CAPSULE_PRO_MANIFEST_PROJECTION.md for generator contract
 * See: .specify/memory/AGENTS.md for code generation workflow
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const GENERATED_HEADER = "// Generated by Capsule-Pro Manifest Generator v0.1.0";
// Resolve to project root from test file location
const __filename = fileURLToPath(import.meta.url);
const PROJECT_ROOT = join(dirname(__filename), "../../../..");
const MANUAL_INTEGRATION_DIR = join(
  PROJECT_ROOT,
  "apps/api/src/app/api/kitchen/manifest"
);

describe("Manifest Code Generation Inventory", () => {
  it("reports surface area of manual vs generated integration (non-blocking)", () => {
    // Check if the manifest API directory exists
    if (!existsSync(MANUAL_INTEGRATION_DIR)) {
      console.info("\nℹ️  No manifest API directory found - inventory empty.\n");
      return;
    }

    const files = getAllRouteFiles(MANUAL_INTEGRATION_DIR);
    const manualFiles: string[] = [];
    const generatedFiles: string[] = [];

    for (const file of files) {
      const content = readFileSync(file, "utf-8");

      if (content.includes(GENERATED_HEADER)) {
        generatedFiles.push(file);
      } else {
        manualFiles.push(file);
      }
    }

    const totalFiles = files.length;
    const generatedCount = generatedFiles.length;
    const manualCount = manualFiles.length;
    const migrationProgress =
      totalFiles > 0 ? ((generatedCount / totalFiles) * 100).toFixed(1) : "0.0";

    // Inventory Report
    console.info("\n");
    console.info("─".repeat(80));
    console.info("📊 Manifest Integration Surface Area Inventory");
    console.info("─".repeat(80));
    console.info("\n");
    console.info(`Total Route Files:       ${totalFiles}`);
    console.info(`Generated Routes:        ${generatedCount}`);
    console.info(`Manual Routes:           ${manualCount}`);
    console.info(`Migration Progress:      ${migrationProgress}%`);
    console.info("\n");

    if (manualFiles.length > 0) {
      console.info("Manual Integration Files:");
      console.info("\n");
      for (const file of manualFiles) {
        const relativePath = file.replace(PROJECT_ROOT, "").replace(/\\/g, "/");
        console.info(`  • ${relativePath}`);
      }
      console.info("\n");
    }

    if (generatedFiles.length > 0) {
      console.info("Generated Integration Files:");
      console.info("\n");
      for (const file of generatedFiles) {
        const relativePath = file.replace(PROJECT_ROOT, "").replace(/\\/g, "/");
        console.info(`  ✓ ${relativePath}`);
      }
      console.info("\n");
    }

    console.info(
      "Generator Status: Pre-pilot (Capsule-Pro projection not yet implemented)"
    );
    console.info("\n");
    console.info(
      "See .specify/memory/CAPSULE_PRO_MANIFEST_PROJECTION.md for generator contract"
    );
    console.info("─".repeat(80));
    console.info("\n");

    // This test always passes - it's inventory only
    expect(true).toBe(true);
  });

  it("provides workflow information (informational)", () => {
    console.info("\n");
    console.info("ℹ️  Code Generation Workflow (Preferred for New Features)");
    console.info("\n");
    console.info(
      "  1. Edit the manifest spec (e.g., packages/kitchen-ops/manifests/recipe-rules.manifest)"
    );
    console.info(
      "  2. Run: npx tsx packages/manifest/bin/compile.ts <file>.manifest --output ./generated"
    );
    console.info("  3. Review and use the generated code");
    console.info("\n");
    console.info(
      "See .specify/memory/AGENTS.md for when to use code generation vs manual integration"
    );
    console.info("\n");

    // This test always passes - it's informational only
    expect(true).toBe(true);
  });
});

/**
 * Recursively get all TypeScript route files in a directory
 */
function getAllRouteFiles(dir: string, files: string[] = []): string[] {
  if (!existsSync(dir)) {
    return files;
  }

  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      getAllRouteFiles(fullPath, files);
    } else if (entry.isFile() && /\.(ts|tsx)$/.test(entry.name)) {
      files.push(fullPath);
    }
  }

  return files;
}
