// GENERATED by manifest:generate-hooks — DO NOT EDIT. Domain chunk: finance.
// Star-imports ONLY this domain's client chunk so the bundle excludes other domains.
import { useQuery, useMutation, useQueryClient, type UseQueryOptions, type UseMutationOptions } from "@tanstack/react-query";
import * as client from "../manifest-client/finance.generated";
import type { PaginatedResponse } from "../manifest-client/core.generated";
import { executeCommand, type CommandEnvelope } from "../manifest-client";
import { queryKeys } from "./core.generated";
import type { BankAccount, Budget, ChartOfAccount, CollectionAction, CollectionCase, CollectionPaymentPlan, EmployeeDeduction, Invoice, LaborBudget, Payment, PaymentMethod, PaymentRefundAttempt, PayrollApprovalHistory, PayrollPeriod, PayrollRun, RevenueRecognitionLine, RevenueRecognitionSchedule } from "../manifest-types.generated";

// List hooks (useEntityList)
export function useBankAccountList(
  options?: Omit<UseQueryOptions<PaginatedResponse<BankAccount>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.bankAccount.lists(),
    queryFn: () => client.listBankAccounts(),
    staleTime: 30_000,
    ...options,
  });
}

export function useBudgetList(
  options?: Omit<UseQueryOptions<PaginatedResponse<Budget>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.budget.lists(),
    queryFn: () => client.listBudgets(),
    staleTime: 30_000,
    ...options,
  });
}

export function useChartOfAccountList(
  options?: Omit<UseQueryOptions<PaginatedResponse<ChartOfAccount>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.chartOfAccount.lists(),
    queryFn: () => client.listChartOfAccounts(),
    staleTime: 30_000,
    ...options,
  });
}

export function useCollectionActionList(
  options?: Omit<UseQueryOptions<PaginatedResponse<CollectionAction>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.collectionAction.lists(),
    queryFn: () => client.listCollectionActions(),
    staleTime: 30_000,
    ...options,
  });
}

export function useCollectionCaseList(
  options?: Omit<UseQueryOptions<PaginatedResponse<CollectionCase>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.collectionCase.lists(),
    queryFn: () => client.listCollectionCases(),
    staleTime: 30_000,
    ...options,
  });
}

export function useCollectionPaymentPlanList(
  options?: Omit<UseQueryOptions<PaginatedResponse<CollectionPaymentPlan>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.collectionPaymentPlan.lists(),
    queryFn: () => client.listCollectionPaymentPlans(),
    staleTime: 30_000,
    ...options,
  });
}

export function useEmployeeDeductionList(
  options?: Omit<UseQueryOptions<PaginatedResponse<EmployeeDeduction>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.employeeDeduction.lists(),
    queryFn: () => client.listEmployeeDeductions(),
    staleTime: 30_000,
    ...options,
  });
}

export function useInvoiceList(
  options?: Omit<UseQueryOptions<PaginatedResponse<Invoice>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.invoice.lists(),
    queryFn: () => client.listInvoices(),
    staleTime: 30_000,
    ...options,
  });
}

export function useLaborBudgetList(
  options?: Omit<UseQueryOptions<PaginatedResponse<LaborBudget>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.laborBudget.lists(),
    queryFn: () => client.listLaborBudgets(),
    staleTime: 30_000,
    ...options,
  });
}

export function usePaymentList(
  options?: Omit<UseQueryOptions<PaginatedResponse<Payment>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payment.lists(),
    queryFn: () => client.listPayments(),
    staleTime: 30_000,
    ...options,
  });
}

export function usePaymentMethodList(
  options?: Omit<UseQueryOptions<PaginatedResponse<PaymentMethod>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.paymentMethod.lists(),
    queryFn: () => client.listPaymentMethods(),
    staleTime: 30_000,
    ...options,
  });
}

export function usePaymentRefundAttemptList(
  options?: Omit<UseQueryOptions<PaginatedResponse<PaymentRefundAttempt>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.paymentRefundAttempt.lists(),
    queryFn: () => client.listPaymentRefundAttempts(),
    staleTime: 30_000,
    ...options,
  });
}

export function usePayrollPeriodList(
  options?: Omit<UseQueryOptions<PaginatedResponse<PayrollPeriod>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payrollPeriod.lists(),
    queryFn: () => client.listPayrollPeriods(),
    staleTime: 30_000,
    ...options,
  });
}

export function usePayrollRunList(
  options?: Omit<UseQueryOptions<PaginatedResponse<PayrollRun>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payrollRun.lists(),
    queryFn: () => client.listPayrollRuns(),
    staleTime: 30_000,
    ...options,
  });
}

export function useRevenueRecognitionLineList(
  options?: Omit<UseQueryOptions<PaginatedResponse<RevenueRecognitionLine>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.revenueRecognitionLine.lists(),
    queryFn: () => client.listRevenueRecognitionLines(),
    staleTime: 30_000,
    ...options,
  });
}

export function useRevenueRecognitionScheduleList(
  options?: Omit<UseQueryOptions<PaginatedResponse<RevenueRecognitionSchedule>, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.revenueRecognitionSchedule.lists(),
    queryFn: () => client.listRevenueRecognitionSchedules(),
    staleTime: 30_000,
    ...options,
  });
}

// Detail hooks (useEntityDetail)
export function useBankAccountDetail(
  id: string,
  options?: Omit<UseQueryOptions<BankAccount | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.bankAccount.detail(id),
    queryFn: () => client.getBankAccount(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useBudgetDetail(
  id: string,
  options?: Omit<UseQueryOptions<Budget | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.budget.detail(id),
    queryFn: () => client.getBudget(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useChartOfAccountDetail(
  id: string,
  options?: Omit<UseQueryOptions<ChartOfAccount | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.chartOfAccount.detail(id),
    queryFn: () => client.getChartOfAccount(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useCollectionActionDetail(
  id: string,
  options?: Omit<UseQueryOptions<CollectionAction | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.collectionAction.detail(id),
    queryFn: () => client.getCollectionAction(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useCollectionCaseDetail(
  id: string,
  options?: Omit<UseQueryOptions<CollectionCase | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.collectionCase.detail(id),
    queryFn: () => client.getCollectionCase(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useCollectionPaymentPlanDetail(
  id: string,
  options?: Omit<UseQueryOptions<CollectionPaymentPlan | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.collectionPaymentPlan.detail(id),
    queryFn: () => client.getCollectionPaymentPlan(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useEmployeeDeductionDetail(
  id: string,
  options?: Omit<UseQueryOptions<EmployeeDeduction | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.employeeDeduction.detail(id),
    queryFn: () => client.getEmployeeDeduction(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useInvoiceDetail(
  id: string,
  options?: Omit<UseQueryOptions<Invoice | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.invoice.detail(id),
    queryFn: () => client.getInvoice(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useLaborBudgetDetail(
  id: string,
  options?: Omit<UseQueryOptions<LaborBudget | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.laborBudget.detail(id),
    queryFn: () => client.getLaborBudget(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function usePaymentDetail(
  id: string,
  options?: Omit<UseQueryOptions<Payment | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payment.detail(id),
    queryFn: () => client.getPayment(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function usePaymentMethodDetail(
  id: string,
  options?: Omit<UseQueryOptions<PaymentMethod | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.paymentMethod.detail(id),
    queryFn: () => client.getPaymentMethod(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function usePaymentRefundAttemptDetail(
  id: string,
  options?: Omit<UseQueryOptions<PaymentRefundAttempt | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.paymentRefundAttempt.detail(id),
    queryFn: () => client.getPaymentRefundAttempt(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function usePayrollApprovalHistoryDetail(
  id: string,
  options?: Omit<UseQueryOptions<PayrollApprovalHistory | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payrollApprovalHistory.detail(id),
    queryFn: () => client.getPayrollApprovalHistory(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function usePayrollPeriodDetail(
  id: string,
  options?: Omit<UseQueryOptions<PayrollPeriod | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payrollPeriod.detail(id),
    queryFn: () => client.getPayrollPeriod(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function usePayrollRunDetail(
  id: string,
  options?: Omit<UseQueryOptions<PayrollRun | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.payrollRun.detail(id),
    queryFn: () => client.getPayrollRun(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useRevenueRecognitionLineDetail(
  id: string,
  options?: Omit<UseQueryOptions<RevenueRecognitionLine | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.revenueRecognitionLine.detail(id),
    queryFn: () => client.getRevenueRecognitionLine(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

export function useRevenueRecognitionScheduleDetail(
  id: string,
  options?: Omit<UseQueryOptions<RevenueRecognitionSchedule | undefined, Error>, "queryKey" | "queryFn">,
) {
  return useQuery({
    queryKey: queryKeys.revenueRecognitionSchedule.detail(id),
    queryFn: () => client.getRevenueRecognitionSchedule(id),
    enabled: !!id,
    staleTime: 30_000,
    ...options,
  });
}

// Command mutation hooks (useEntityCommandNameMutation)
export function useBankAccountCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBankAccountRemoveMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "remove", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBankAccountMarkDefaultMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "markDefault", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBankAccountUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBankAccountVerifyMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "verify", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBankAccountVerifyFailedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "verifyFailed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBankAccountRetryVerificationMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<BankAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<BankAccount>("BankAccount", "retryVerification", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bankAccount.all });
    },
    ...options,
  });
}

export function useBudgetCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetRemoveMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "remove", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetApproveMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "approve", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetLockMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "lock", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetAddLineItemMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "addLineItem", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetRecordVarianceMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "recordVariance", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useBudgetRefreshMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Budget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Budget>("Budget", "refresh", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.budget.all });
    },
    ...options,
  });
}

export function useChartOfAccountCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<ChartOfAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<ChartOfAccount>("ChartOfAccount", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.chartOfAccount.all });
    },
    ...options,
  });
}

export function useChartOfAccountUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<ChartOfAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<ChartOfAccount>("ChartOfAccount", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.chartOfAccount.all });
    },
    ...options,
  });
}

export function useChartOfAccountDeactivateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<ChartOfAccount>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<ChartOfAccount>("ChartOfAccount", "deactivate", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.chartOfAccount.all });
    },
    ...options,
  });
}

export function useCollectionActionCompleteMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionAction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionAction>("CollectionAction", "complete", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionAction.all });
    },
    ...options,
  });
}

export function useCollectionActionFailMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionAction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionAction>("CollectionAction", "fail", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionAction.all });
    },
    ...options,
  });
}

export function useCollectionActionSkipMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionAction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionAction>("CollectionAction", "skip", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionAction.all });
    },
    ...options,
  });
}

export function useCollectionActionRescheduleMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionAction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionAction>("CollectionAction", "reschedule", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionAction.all });
    },
    ...options,
  });
}

export function useCollectionCaseCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseAssignToMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "assignTo", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseUpdateStatusMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "updateStatus", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseSettleMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "settle", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseRecordPaymentMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "recordPayment", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseMarkResolvedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "markResolved", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseEscalateDunningMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "escalateDunning", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseEscalateToLegalMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "escalateToLegal", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseSetUrgentPriorityMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "setUrgentPriority", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseSetHighPriorityMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "setHighPriority", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseResetDunningMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "resetDunning", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseCreatePaymentPlanMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "createPaymentPlan", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseMarkDisputedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "markDisputed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseResolveDisputeMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "resolveDispute", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseEscalateToLegalWithDetailsMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "escalateToLegalWithDetails", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseWriteOffMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "writeOff", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseUpdateAgingMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "updateAging", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseSetPriorityMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "setPriority", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionCaseCloseMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionCase>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionCase>("CollectionCase", "close", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionCase.all });
    },
    ...options,
  });
}

export function useCollectionPaymentPlanRecordInstallmentMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionPaymentPlan>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionPaymentPlan>("CollectionPaymentPlan", "recordInstallment", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionPaymentPlan.all });
    },
    ...options,
  });
}

export function useCollectionPaymentPlanMarkCompletedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionPaymentPlan>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionPaymentPlan>("CollectionPaymentPlan", "markCompleted", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionPaymentPlan.all });
    },
    ...options,
  });
}

export function useCollectionPaymentPlanMarkDefaultedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionPaymentPlan>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionPaymentPlan>("CollectionPaymentPlan", "markDefaulted", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionPaymentPlan.all });
    },
    ...options,
  });
}

export function useCollectionPaymentPlanCancelMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionPaymentPlan>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionPaymentPlan>("CollectionPaymentPlan", "cancel", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionPaymentPlan.all });
    },
    ...options,
  });
}

export function useCollectionPaymentPlanModifyMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<CollectionPaymentPlan>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<CollectionPaymentPlan>("CollectionPaymentPlan", "modify", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.collectionPaymentPlan.all });
    },
    ...options,
  });
}

export function useEmployeeDeductionCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<EmployeeDeduction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<EmployeeDeduction>("EmployeeDeduction", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.employeeDeduction.all });
    },
    ...options,
  });
}

export function useEmployeeDeductionUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<EmployeeDeduction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<EmployeeDeduction>("EmployeeDeduction", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.employeeDeduction.all });
    },
    ...options,
  });
}

export function useEmployeeDeductionDeactivateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<EmployeeDeduction>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<EmployeeDeduction>("EmployeeDeduction", "deactivate", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.employeeDeduction.all });
    },
    ...options,
  });
}

export function useInvoiceUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceSendMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "send", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceMarkViewedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "markViewed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceApplyPaymentMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "applyPayment", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceMarkAsPaidMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "markAsPaid", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceRecordRefundMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "recordRefund", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceMarkOverdueMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "markOverdue", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceSendReminderMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "sendReminder", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceVoidInvoiceMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "voidInvoice", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceWriteOffMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "writeOff", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useInvoiceUpdateLineItemsMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Invoice>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Invoice>("Invoice", "updateLineItems", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.invoice.all });
    },
    ...options,
  });
}

export function useLaborBudgetCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<LaborBudget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<LaborBudget>("LaborBudget", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.laborBudget.all });
    },
    ...options,
  });
}

export function useLaborBudgetUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<LaborBudget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<LaborBudget>("LaborBudget", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.laborBudget.all });
    },
    ...options,
  });
}

export function useLaborBudgetApproveMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<LaborBudget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<LaborBudget>("LaborBudget", "approve", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.laborBudget.all });
    },
    ...options,
  });
}

export function useLaborBudgetRecordActualMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<LaborBudget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<LaborBudget>("LaborBudget", "recordActual", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.laborBudget.all });
    },
    ...options,
  });
}

export function useLaborBudgetCloseMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<LaborBudget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<LaborBudget>("LaborBudget", "close", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.laborBudget.all });
    },
    ...options,
  });
}

export function useLaborBudgetSoftDeleteMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<LaborBudget>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<LaborBudget>("LaborBudget", "softDelete", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.laborBudget.all });
    },
    ...options,
  });
}

export function usePaymentProcessMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "process", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentProcessFailedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "processFailed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentRefundMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "refund", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentPartialRefundMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "partialRefund", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentMarkChargebackMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "markChargeback", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentUpdateFraudStatusMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "updateFraudStatus", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentMarkFraudReviewedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "markFraudReviewed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentMarkFraudPassedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "markFraudPassed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentMarkFraudFailedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "markFraudFailed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentMarkAcceptedNotAppliedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<Payment>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<Payment>("Payment", "markAcceptedNotApplied", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payment.all });
    },
    ...options,
  });
}

export function usePaymentMethodCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodMarkAsDefaultMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "markAsDefault", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodMarkNotDefaultMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "markNotDefault", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodMarkExpiredMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "markExpired", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodMarkInvalidMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "markInvalid", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodFlagForFraudMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "flagForFraud", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodVerifyMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "verify", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodMarkVerificationFailedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "markVerificationFailed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodUpdateTokenMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "updateToken", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodUpdateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "update", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentMethodRemoveMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentMethod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentMethod>("PaymentMethod", "remove", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentMethod.all });
    },
    ...options,
  });
}

export function usePaymentRefundAttemptCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentRefundAttempt>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentRefundAttempt>("PaymentRefundAttempt", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentRefundAttempt.all });
    },
    ...options,
  });
}

export function usePaymentRefundAttemptMarkSucceededMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentRefundAttempt>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentRefundAttempt>("PaymentRefundAttempt", "markSucceeded", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentRefundAttempt.all });
    },
    ...options,
  });
}

export function usePaymentRefundAttemptMarkFailedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PaymentRefundAttempt>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PaymentRefundAttempt>("PaymentRefundAttempt", "markFailed", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.paymentRefundAttempt.all });
    },
    ...options,
  });
}

export function usePayrollApprovalHistoryCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollApprovalHistory>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollApprovalHistory>("PayrollApprovalHistory", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollApprovalHistory.all });
    },
    ...options,
  });
}

export function usePayrollPeriodCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollPeriod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollPeriod>("PayrollPeriod", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollPeriod.all });
    },
    ...options,
  });
}

export function usePayrollPeriodCloseMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollPeriod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollPeriod>("PayrollPeriod", "close", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollPeriod.all });
    },
    ...options,
  });
}

export function usePayrollPeriodReopenMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollPeriod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollPeriod>("PayrollPeriod", "reopen", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollPeriod.all });
    },
    ...options,
  });
}

export function usePayrollPeriodLockMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollPeriod>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollPeriod>("PayrollPeriod", "lock", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollPeriod.all });
    },
    ...options,
  });
}

export function usePayrollRunCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollRun>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollRun>("PayrollRun", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollRun.all });
    },
    ...options,
  });
}

export function usePayrollRunProcessMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollRun>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollRun>("PayrollRun", "process", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollRun.all });
    },
    ...options,
  });
}

export function usePayrollRunApproveMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollRun>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollRun>("PayrollRun", "approve", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollRun.all });
    },
    ...options,
  });
}

export function usePayrollRunRejectMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollRun>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollRun>("PayrollRun", "reject", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollRun.all });
    },
    ...options,
  });
}

export function usePayrollRunMarkPaidMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<PayrollRun>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<PayrollRun>("PayrollRun", "markPaid", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.payrollRun.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionLineCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionLine>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionLine>("RevenueRecognitionLine", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionLine.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionLineRecognizeMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionLine>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionLine>("RevenueRecognitionLine", "recognize", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionLine.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionLineSkipMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionLine>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionLine>("RevenueRecognitionLine", "skip", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionLine.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionLineCancelMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionLine>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionLine>("RevenueRecognitionLine", "cancel", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionLine.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionLineReverseMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionLine>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionLine>("RevenueRecognitionLine", "reverse", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionLine.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleCreateMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "create", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleStartRecognitionMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "startRecognition", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleRecognizeAmountMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "recognizeAmount", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleCompleteIfFullyRecognizedMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "completeIfFullyRecognized", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleRecognizeMilestoneMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "recognizeMilestone", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleCompleteIfAllMilestonesMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "completeIfAllMilestones", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleRecognizePercentageMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "recognizePercentage", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleCompleteIfPercentageFullMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "completeIfPercentageFull", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionSchedulePauseMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "pause", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleResumeMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "resume", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleCancelMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "cancel", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleAdjustScheduleMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "adjustSchedule", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}

export function useRevenueRecognitionScheduleReverseRecognitionMutation(
  options?: Omit<UseMutationOptions<CommandEnvelope<RevenueRecognitionSchedule>, Error, Record<string, unknown>>, "mutationFn">,
) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (input) => executeCommand<RevenueRecognitionSchedule>("RevenueRecognitionSchedule", "reverseRecognition", input),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.revenueRecognitionSchedule.all });
    },
    ...options,
  });
}
