// GENERATED by manifest:generate-hooks — DO NOT EDIT. Barrel.
export * from "./core.generated";
export * from "./events.generated";
export * from "./kitchen.generated";
export * from "./finance.generated";
export * from "./staffing.generated";
export * from "./crm.generated";
export * from "./logistics.generated";
