import type { MenuCatalogItem } from "../types/menu";

export const menuCatalog: MenuCatalogItem[] = [
  // ── Appetizers ──
  {
    id: "app-bruschetta",
    name: "Heirloom Tomato Bruschetta",
    description:
      "Grilled sourdough, marinated heirloom tomatoes, basil, aged balsamic",
    category: "appetizer",
    dietaryFlags: ["vegan", "dairy-free", "nut-free"],
    compatibleStyles: [
      "plated",
      "buffet",
      "stations",
      "family-style",
      "cocktail-reception",
    ],
    seasons: ["spring", "summer"],
    pricePerPerson: 6,
  },
  {
    id: "app-burrata",
    name: "Burrata & Stone Fruit",
    description:
      "Creamy burrata, seasonal stone fruit, arugula, honey, pistachios",
    category: "appetizer",
    dietaryFlags: ["vegetarian", "gluten-free"],
    compatibleStyles: [
      "plated",
      "buffet",
      "family-style",
      "cocktail-reception",
    ],
    seasons: ["summer", "fall"],
    pricePerPerson: 9,
  },
  {
    id: "app-crab-cakes",
    name: "Pan-Seared Crab Cakes",
    description: "Jumbo lump crab, Old Bay remoulade, microgreens",
    category: "appetizer",
    dietaryFlags: ["gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "stations", "cocktail-reception"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 12,
  },
  {
    id: "app-mushroom-soup",
    name: "Wild Mushroom Bisque",
    description: "Foraged mushroom blend, truffle cream, chive oil",
    category: "appetizer",
    dietaryFlags: ["vegetarian", "gluten-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style"],
    seasons: ["fall", "winter"],
    pricePerPerson: 7,
  },
  {
    id: "app-tuna-tartare",
    name: "Ahi Tuna Tartare",
    description:
      "Sushi-grade tuna, avocado, sesame-soy vinaigrette, wonton crisp",
    category: "appetizer",
    dietaryFlags: ["dairy-free", "nut-free"],
    compatibleStyles: ["plated", "stations", "cocktail-reception"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 14,
  },
  {
    id: "app-beet-salad",
    name: "Roasted Beet & Goat Cheese Salad",
    description:
      "Red and golden beets, whipped chevre, candied walnuts, citrus vinaigrette",
    category: "appetizer",
    dietaryFlags: ["vegetarian", "gluten-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["fall", "winter", "spring"],
    pricePerPerson: 7,
  },
  {
    id: "app-spring-rolls",
    name: "Fresh Vietnamese Spring Rolls",
    description: "Rice paper, vermicelli, herbs, shrimp, peanut dipping sauce",
    category: "appetizer",
    dietaryFlags: ["gluten-free", "dairy-free"],
    compatibleStyles: ["buffet", "stations", "cocktail-reception", "drop-off"],
    seasons: ["spring", "summer"],
    pricePerPerson: 6,
  },
  {
    id: "app-flatbread",
    name: "Seasonal Flatbread",
    description: "Crispy flatbread with rotating seasonal toppings, herb oil",
    category: "appetizer",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: [
      "buffet",
      "stations",
      "family-style",
      "cocktail-reception",
      "drop-off",
    ],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 5,
  },

  // ── Mains ──
  {
    id: "main-filet",
    name: "Filet Mignon",
    description: "Center-cut filet, compound butter, roasted garlic jus",
    category: "main",
    dietaryFlags: ["gluten-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 38,
  },
  {
    id: "main-salmon",
    name: "Pan-Roasted Atlantic Salmon",
    description: "Citrus-herb glaze, dill cream, crispy capers",
    category: "main",
    dietaryFlags: ["gluten-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "stations"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 28,
  },
  {
    id: "main-chicken",
    name: "Herb-Roasted Airline Chicken",
    description: "Statler breast, lemon pan sauce, wilted greens",
    category: "main",
    dietaryFlags: ["gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 22,
  },
  {
    id: "main-short-rib",
    name: "Braised Short Rib",
    description:
      "48-hour braised beef short rib, red wine reduction, root vegetables",
    category: "main",
    dietaryFlags: ["gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "stations"],
    seasons: ["fall", "winter"],
    pricePerPerson: 34,
  },
  {
    id: "main-lamb",
    name: "Rack of Lamb",
    description: "Herb-crusted Colorado lamb, mint gremolata, natural jus",
    category: "main",
    dietaryFlags: ["gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "family-style"],
    seasons: ["spring", "fall", "winter"],
    pricePerPerson: 36,
  },
  {
    id: "main-risotto",
    name: "Wild Mushroom Risotto",
    description: "Arborio rice, seasonal mushrooms, parmesan, truffle oil",
    category: "main",
    dietaryFlags: ["vegetarian", "gluten-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "stations"],
    seasons: ["fall", "winter"],
    pricePerPerson: 18,
  },
  {
    id: "main-tofu-bowl",
    name: "Glazed Tofu & Grain Bowl",
    description: "Miso-ginger tofu, farro, roasted vegetables, tahini drizzle",
    category: "main",
    dietaryFlags: ["vegan", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "stations", "drop-off"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 16,
  },
  {
    id: "main-sea-bass",
    name: "Chilean Sea Bass",
    description: "Soy-glazed sea bass, bok choy, jasmine rice, ginger broth",
    category: "main",
    dietaryFlags: ["gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 42,
  },
  {
    id: "main-bbq-brisket",
    name: "Smoked Brisket",
    description: "Slow-smoked beef brisket, house BBQ sauce, pickled onions",
    category: "main",
    dietaryFlags: ["gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["buffet", "stations", "family-style", "drop-off"],
    seasons: ["summer", "fall"],
    pricePerPerson: 24,
  },

  // ── Sides ──
  {
    id: "side-roast-veg",
    name: "Seasonal Roasted Vegetables",
    description: "Market vegetables, herb oil, flaky sea salt",
    category: "side",
    dietaryFlags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: [
      "plated",
      "buffet",
      "family-style",
      "drop-off",
      "stations",
    ],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 6,
  },
  {
    id: "side-mashed",
    name: "Yukon Gold Mashed Potatoes",
    description: "Butter-whipped, roasted garlic, chive",
    category: "side",
    dietaryFlags: ["vegetarian", "gluten-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["fall", "winter"],
    pricePerPerson: 5,
  },
  {
    id: "side-grains",
    name: "Herbed Grain Pilaf",
    description:
      "Farro and quinoa blend, herbs, toasted almonds, dried cranberries",
    category: "side",
    dietaryFlags: ["vegan", "dairy-free"],
    compatibleStyles: [
      "plated",
      "buffet",
      "family-style",
      "drop-off",
      "stations",
    ],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 5,
  },
  {
    id: "side-caesar",
    name: "Classic Caesar Salad",
    description:
      "Crisp romaine, house-made croutons, shaved parmesan, anchovy dressing",
    category: "side",
    dietaryFlags: ["nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 5,
  },
  {
    id: "side-green-beans",
    name: "Haricots Verts Almondine",
    description: "French green beans, toasted almonds, brown butter, lemon",
    category: "side",
    dietaryFlags: ["vegetarian", "gluten-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["spring", "summer", "fall"],
    pricePerPerson: 5,
  },
  {
    id: "side-mac-cheese",
    name: "Truffle Mac & Cheese",
    description: "Cavatappi, three-cheese blend, truffle oil, herb breadcrumb",
    category: "side",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["buffet", "family-style", "drop-off", "stations"],
    seasons: ["fall", "winter"],
    pricePerPerson: 7,
  },
  {
    id: "side-corn-succotash",
    name: "Summer Corn Succotash",
    description: "Sweet corn, lima beans, cherry tomatoes, basil",
    category: "side",
    dietaryFlags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["summer"],
    pricePerPerson: 5,
  },

  // ── Desserts ──
  {
    id: "dessert-chocolate",
    name: "Dark Chocolate Torte",
    description: "Flourless chocolate cake, salted caramel, whipped cream",
    category: "dessert",
    dietaryFlags: ["vegetarian", "gluten-free", "nut-free"],
    compatibleStyles: [
      "plated",
      "buffet",
      "family-style",
      "stations",
      "drop-off",
    ],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 8,
  },
  {
    id: "dessert-cheesecake",
    name: "New York Cheesecake",
    description: "Classic creamy cheesecake, seasonal fruit compote",
    category: "dessert",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 7,
  },
  {
    id: "dessert-panna-cotta",
    name: "Vanilla Bean Panna Cotta",
    description: "Silky vanilla custard, berry coulis, mint",
    category: "dessert",
    dietaryFlags: ["vegetarian", "gluten-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "stations"],
    seasons: ["spring", "summer"],
    pricePerPerson: 7,
  },
  {
    id: "dessert-fruit-tart",
    name: "Seasonal Fruit Tart",
    description: "Butter pastry, pastry cream, glazed seasonal fruits",
    category: "dessert",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style", "drop-off"],
    seasons: ["spring", "summer", "fall"],
    pricePerPerson: 7,
  },
  {
    id: "dessert-sorbet",
    name: "Artisan Sorbet Trio",
    description: "Three seasonal sorbets, fresh berries, mint",
    category: "dessert",
    dietaryFlags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    compatibleStyles: ["plated", "buffet", "stations"],
    seasons: ["spring", "summer"],
    pricePerPerson: 6,
  },
  {
    id: "dessert-tiramisu",
    name: "Classic Tiramisu",
    description: "Espresso-soaked ladyfingers, mascarpone, cocoa",
    category: "dessert",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["plated", "buffet", "family-style"],
    seasons: ["fall", "winter"],
    pricePerPerson: 8,
  },

  // ── Late Night ──
  {
    id: "late-sliders",
    name: "Mini Burger Sliders",
    description: "Wagyu blend, American cheese, pickles, special sauce",
    category: "late-night",
    dietaryFlags: ["nut-free"],
    compatibleStyles: ["stations", "buffet", "cocktail-reception"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 8,
  },
  {
    id: "late-tacos",
    name: "Street Taco Bar",
    description: "Carne asada, al pastor, salsa verde, fresh toppings",
    category: "late-night",
    dietaryFlags: ["nut-free", "dairy-free"],
    compatibleStyles: ["stations", "buffet"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 9,
  },
  {
    id: "late-pizza",
    name: "Wood-Fired Pizza Station",
    description: "Margherita, pepperoni, seasonal veggie — made to order",
    category: "late-night",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["stations", "buffet"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 8,
  },
  {
    id: "late-fries",
    name: "Truffle Fries & Dipping Sauces",
    description: "Hand-cut fries, truffle oil, parmesan, three sauces",
    category: "late-night",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["stations", "buffet", "cocktail-reception"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 5,
  },
  {
    id: "late-donuts",
    name: "Mini Donut Wall",
    description: "Assorted mini donuts, glazes, toppings bar",
    category: "late-night",
    dietaryFlags: ["vegetarian", "nut-free"],
    compatibleStyles: ["stations", "buffet", "cocktail-reception"],
    seasons: ["spring", "summer", "fall", "winter"],
    pricePerPerson: 6,
  },
];

export const MENU_DIRECTIONS = [
  {
    value: "classic-american",
    label: "Classic American",
    description: "Timeless comfort elevated with premium ingredients",
  },
  {
    value: "mediterranean",
    label: "Mediterranean",
    description: "Fresh, bright flavors from the coast",
  },
  {
    value: "farm-to-table",
    label: "Farm to Table",
    description: "Seasonal, local, and ingredient-driven",
  },
  {
    value: "modern-fusion",
    label: "Modern Fusion",
    description: "Creative cross-cultural combinations",
  },
  {
    value: "southern-comfort",
    label: "Southern Comfort",
    description: "Warm, generous, soul-satisfying dishes",
  },
  {
    value: "coastal-seafood",
    label: "Coastal Seafood",
    description: "Ocean-forward with fresh catches",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  appetizer: "Appetizers",
  main: "Main Courses",
  side: "Sides & Accompaniments",
  dessert: "Desserts",
  "late-night": "Late Night",
};

export const CATEGORY_ORDER: string[] = [
  "appetizer",
  "main",
  "side",
  "dessert",
  "late-night",
];
