// GENERATED by manifest:client — DO NOT EDIT. Domain chunk: crm.
// Matches Capsule conventions (manifest/capsule-conventions.json).
import { apiFetch } from "@/app/lib/api";
import { executeCommand } from "@/app/lib/manifest-client";
import type { PaginatedResponse } from "./core.generated";
import type { Client, ClientContact, ClientInteraction, ClientPreference, CrmScoringRule, Deal, InteractionAttachment, Lead, Proposal, ProposalLineItem, ProposalTemplate } from "../manifest-types.generated";

// Command input types (generated from IR parameters)
export interface ClientArchiveInput {
  id?: string;
  reason?: string;
  userId?: string;
}
export interface ClientCreateInput {
  clientType?: string;
  companyName?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  website?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  stateProvince?: string;
  postalCode?: string;
  countryCode?: string;
  defaultPaymentTerms?: number;
  taxExempt?: boolean;
  taxId?: string;
  notes?: string;
  tags?: string[];
  source?: string;
  assignedTo?: string;
}
export interface ClientReactivateInput {
  id?: string;
  userId?: string;
}
export interface ClientUpdateInput {
  id?: string;
  companyName?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  website?: string;
  addressLine1?: string;
  addressLine2?: string;
  city?: string;
  stateProvince?: string;
  postalCode?: string;
  countryCode?: string;
  defaultPaymentTerms?: number;
  taxExempt?: boolean;
  taxId?: string;
  notes?: string;
  tags?: string[];
  source?: string;
  assignedTo?: string;
}
export interface ClientContactCreateInput {
  clientId?: string;
  firstName?: string;
  lastName?: string;
  title?: string;
  email?: string;
  phone?: string;
  phoneMobile?: string;
  isPrimary?: boolean;
  isBillingContact?: boolean;
  notes?: string;
}
export interface ClientContactRemoveInput {
  id?: string;
  reason?: string;
  userId?: string;
}
export interface ClientContactSetPrimaryInput {
  id?: string;
  userId?: string;
}
export interface ClientContactUpdateInput {
  id?: string;
  firstName?: string;
  lastName?: string;
  title?: string;
  email?: string;
  phone?: string;
  phoneMobile?: string;
  isBillingContact?: boolean;
  notes?: string;
}
export interface ClientInteractionCompleteInput {
  id?: string;
  completionNotes?: string;
  userId?: string;
}
export interface ClientInteractionCreateInput {
  clientId?: string;
  leadId?: string;
  employeeId?: string;
  interactionType?: string;
  interactionDate?: string;
  subject?: string;
  description?: string;
  followUpDate?: string;
  correlationId?: string;
}
export interface ClientInteractionEscalateInput {
  id?: string;
  escalatedTo?: string;
  reason?: string;
}
export interface ClientInteractionMarkOverdueInput {
  id?: string;
}
export interface ClientInteractionScheduleInput {
  id?: string;
  followUpDate?: string;
  assignedTo?: string;
}
export interface ClientInteractionSoftDeleteInput {
  id?: string;
}
export interface ClientInteractionUpdateInput {
  id?: string;
  interactionType?: string;
  interactionDate?: string;
  subject?: string;
  description?: string;
  followUpDate?: string;
  correlationId?: string;
}
export interface ClientPreferenceCreateInput {
  clientId?: string;
  preferenceType?: string;
  preferenceKey?: string;
  preferenceValue?: string;
  notes?: string;
}
export interface ClientPreferenceRemoveInput {
  id?: string;
  userId?: string;
}
export interface ClientPreferenceUpdateInput {
  id?: string;
  preferenceValue?: string;
  notes?: string;
}
export interface CrmScoringRuleActivateInput {
  id?: string;
}
export interface CrmScoringRuleCreateInput {
  ruleName?: string;
  field?: string;
  condition?: string;
  value?: string;
  points?: number;
  isActive?: boolean;
  priority?: number;
}
export interface CrmScoringRuleDeactivateInput {
  id?: string;
}
export interface CrmScoringRuleSoftDeleteInput {
  id?: string;
}
export interface CrmScoringRuleUpdateInput {
  id?: string;
  ruleName?: string;
  field?: string;
  condition?: string;
  value?: string;
  points?: number;
  isActive?: boolean;
  priority?: number;
}
export interface DealAbandonInput {
  id?: string;
  reason?: string;
}
export interface DealAssignInput {
  id?: string;
  assignedTo?: string;
  assignedBy?: string;
}
export interface DealCloseInput {
  id?: string;
  status?: string;
}
export interface DealCreateInput {
  leadId?: string;
  title?: string;
  value?: number;
  currency?: string;
  stage?: string;
  probability?: number;
  expectedCloseDate?: string;
  assignedTo?: string;
  notes?: string;
}
export interface DealReopenInput {
  id?: string;
  reason?: string;
}
export interface DealUpdateProbabilityInput {
  id?: string;
  probability?: number;
}
export interface DealUpdateStageInput {
  id?: string;
  stage?: string;
  notes?: string;
}
export interface DealUpdateValueInput {
  id?: string;
  value?: number;
}
export interface InteractionAttachmentCreateInput {
  interactionId?: string;
  fileName?: string;
  fileUrl?: string;
  fileType?: string;
  fileSize?: number;
  uploadedBy?: string;
}
export interface InteractionAttachmentRemoveInput {
  id?: string;
  userId?: string;
}
export interface LeadArchiveInput {
  id?: string;
  reason?: string;
  userId?: string;
}
export interface LeadConvertToClientInput {
  id?: string;
  clientId?: string;
  userId?: string;
}
export interface LeadCreateInput {
  source?: string;
  companyName?: string;
  contactName?: string;
  contactEmail?: string;
  contactPhone?: string;
  eventType?: string;
  eventDate?: string;
  estimatedGuests?: number;
  estimatedValue?: number;
  assignedTo?: string;
  notes?: string;
}
export interface LeadDisqualifyInput {
  id?: string;
  reason?: string;
  userId?: string;
}
export interface LeadUpdateInput {
  id?: string;
  companyName?: string;
  contactName?: string;
  contactEmail?: string;
  contactPhone?: string;
  eventType?: string;
  eventDate?: string;
  estimatedGuests?: number;
  estimatedValue?: number;
  status?: string;
  assignedTo?: string;
  notes?: string;
}
export interface ProposalAcceptInput {
  id?: string;
  userId?: string;
  clientId?: string;
  proposalNumber?: string;
  title?: string;
  total?: number;
  eventType?: string;
}
export interface ProposalCreateInput {
  proposalNumber?: string;
  leadId?: string;
  eventId?: string;
  title?: string;
  guestCount?: number;
  taxRate?: number;
  validUntil?: string;
  notes?: string;
  termsAndConditions?: string;
}
export interface ProposalDecrementLineItemCountInput {
  id?: string;
}
export interface ProposalGeneratePublicLinkInput {
  id?: string;
  userId?: string;
}
export interface ProposalIncrementLineItemCountInput {
  id?: string;
}
export interface ProposalMarkViewedInput {
  id?: string;
  viewedByInfo?: string;
}
export interface ProposalRejectInput {
  id?: string;
  reason?: string;
  userId?: string;
}
export interface ProposalRemoveInput {
  id?: string;
  userId?: string;
}
export interface ProposalSendInput {
  id?: string;
  userId?: string;
}
export interface ProposalUpdateInput {
  id?: string;
  title?: string;
  eventDate?: string;
  eventType?: string;
  guestCount?: number;
  venueName?: string;
  venueAddress?: string;
  subtotal?: number;
  taxRate?: number;
  taxAmount?: number;
  discountAmount?: number;
  total?: number;
  validUntil?: string;
  notes?: string;
  termsAndConditions?: string;
}
export interface ProposalWithdrawInput {
  id?: string;
  reason?: string;
  userId?: string;
}
export interface ProposalLineItemCreateInput {
  proposalId?: string;
  itemType?: string;
  category?: string;
  description?: string;
  quantity?: number;
  unitOfMeasure?: string;
  unitPrice?: number;
  sortOrder?: number;
  notes?: string;
}
export interface ProposalLineItemRemoveInput {
  id?: string;
  userId?: string;
}
export interface ProposalLineItemUpdateInput {
  id?: string;
  itemType?: string;
  category?: string;
  description?: string;
  quantity?: number;
  unitOfMeasure?: string;
  unitPrice?: number;
  sortOrder?: number;
  notes?: string;
}
export interface ProposalTemplateActivateInput {
  id?: string;
}
export interface ProposalTemplateCreateInput {
  name?: string;
  description?: string;
  eventType?: string;
  defaultTerms?: string;
  defaultTaxRate?: number;
  defaultNotes?: string;
  defaultLineItems?: string;
  isActive?: boolean;
  isDefault?: boolean;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  fontFamily?: string;
}
export interface ProposalTemplateDeactivateInput {
  id?: string;
}
export interface ProposalTemplateSoftDeleteInput {
  id?: string;
}
export interface ProposalTemplateUpdateInput {
  id?: string;
  name?: string;
  description?: string;
  eventType?: string;
  defaultTerms?: string;
  defaultTaxRate?: number;
  defaultNotes?: string;
  defaultLineItems?: string;
  isActive?: boolean;
  isDefault?: boolean;
  logoUrl?: string;
  primaryColor?: string;
  secondaryColor?: string;
  accentColor?: string;
  fontFamily?: string;
}

export async function listClients(query?: Record<string, string | number>): Promise<PaginatedResponse<Client>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/clients/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list Client (${res.status})`);
  const json = await res.json();
  const data = (json.clients ?? json.data ?? []) as Client[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getClient(id: string): Promise<Client | undefined> {
  const res = await apiFetch(`/api/crm/clients/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get Client (${res.status})`);
  const json = await res.json();
  return (json.client ?? json.data) as Client | undefined;
}
export async function listClientContacts(query?: Record<string, string | number>): Promise<PaginatedResponse<ClientContact>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/client-contacts/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list ClientContact (${res.status})`);
  const json = await res.json();
  const data = (json.clientContacts ?? json.data ?? []) as ClientContact[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getClientContact(id: string): Promise<ClientContact | undefined> {
  const res = await apiFetch(`/api/crm/client-contacts/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get ClientContact (${res.status})`);
  const json = await res.json();
  return (json.clientContact ?? json.data) as ClientContact | undefined;
}
export async function listClientPreferences(query?: Record<string, string | number>): Promise<PaginatedResponse<ClientPreference>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/client-preferences/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list ClientPreference (${res.status})`);
  const json = await res.json();
  const data = (json.clientPreferences ?? json.data ?? []) as ClientPreference[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getClientPreference(id: string): Promise<ClientPreference | undefined> {
  const res = await apiFetch(`/api/crm/client-preferences/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get ClientPreference (${res.status})`);
  const json = await res.json();
  return (json.clientPreference ?? json.data) as ClientPreference | undefined;
}
export async function listLeads(query?: Record<string, string | number>): Promise<PaginatedResponse<Lead>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/leads/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list Lead (${res.status})`);
  const json = await res.json();
  const data = (json.leads ?? json.data ?? []) as Lead[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getLead(id: string): Promise<Lead | undefined> {
  const res = await apiFetch(`/api/crm/leads/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get Lead (${res.status})`);
  const json = await res.json();
  return (json.lead ?? json.data) as Lead | undefined;
}
export async function listProposals(query?: Record<string, string | number>): Promise<PaginatedResponse<Proposal>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/proposals/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list Proposal (${res.status})`);
  const json = await res.json();
  const data = (json.proposals ?? json.data ?? []) as Proposal[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getProposal(id: string): Promise<Proposal | undefined> {
  const res = await apiFetch(`/api/crm/proposals/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get Proposal (${res.status})`);
  const json = await res.json();
  return (json.proposal ?? json.data) as Proposal | undefined;
}
export async function listProposalLineItems(query?: Record<string, string | number>): Promise<PaginatedResponse<ProposalLineItem>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/proposal-line-items/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list ProposalLineItem (${res.status})`);
  const json = await res.json();
  const data = (json.proposalLineItems ?? json.data ?? []) as ProposalLineItem[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getProposalLineItem(id: string): Promise<ProposalLineItem | undefined> {
  const res = await apiFetch(`/api/crm/proposal-line-items/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get ProposalLineItem (${res.status})`);
  const json = await res.json();
  return (json.proposalLineItem ?? json.data) as ProposalLineItem | undefined;
}
export async function listClientInteractions(query?: Record<string, string | number>): Promise<PaginatedResponse<ClientInteraction>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/client-interactions/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list ClientInteraction (${res.status})`);
  const json = await res.json();
  const data = (json.clientInteractions ?? json.data ?? []) as ClientInteraction[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getClientInteraction(id: string): Promise<ClientInteraction | undefined> {
  const res = await apiFetch(`/api/crm/client-interactions/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get ClientInteraction (${res.status})`);
  const json = await res.json();
  return (json.clientInteraction ?? json.data) as ClientInteraction | undefined;
}
export async function listProposalTemplates(query?: Record<string, string | number>): Promise<PaginatedResponse<ProposalTemplate>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/proposal-templates/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list ProposalTemplate (${res.status})`);
  const json = await res.json();
  const data = (json.proposalTemplates ?? json.data ?? []) as ProposalTemplate[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getProposalTemplate(id: string): Promise<ProposalTemplate | undefined> {
  const res = await apiFetch(`/api/crm/proposal-templates/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get ProposalTemplate (${res.status})`);
  const json = await res.json();
  return (json.proposalTemplate ?? json.data) as ProposalTemplate | undefined;
}
export async function listInteractionAttachments(query?: Record<string, string | number>): Promise<PaginatedResponse<InteractionAttachment>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/interaction-attachments/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list InteractionAttachment (${res.status})`);
  const json = await res.json();
  const data = (json.interactionAttachments ?? json.data ?? []) as InteractionAttachment[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getInteractionAttachment(id: string): Promise<InteractionAttachment | undefined> {
  const res = await apiFetch(`/api/crm/interaction-attachments/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get InteractionAttachment (${res.status})`);
  const json = await res.json();
  return (json.interactionAttachment ?? json.data) as InteractionAttachment | undefined;
}
export async function listCrmScoringRules(query?: Record<string, string | number>): Promise<PaginatedResponse<CrmScoringRule>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/scoring-rules/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list CrmScoringRule (${res.status})`);
  const json = await res.json();
  const data = (json.crmScoringRules ?? json.data ?? []) as CrmScoringRule[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getCrmScoringRule(id: string): Promise<CrmScoringRule | undefined> {
  const res = await apiFetch(`/api/crm/scoring-rules/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get CrmScoringRule (${res.status})`);
  const json = await res.json();
  return (json.crmScoringRule ?? json.data) as CrmScoringRule | undefined;
}
export async function listDeals(query?: Record<string, string | number>): Promise<PaginatedResponse<Deal>> {
  const qs = query ? "?" + new URLSearchParams(Object.entries(query).map(([k, v]) => [k, String(v)])).toString() : "";
  const res = await apiFetch(`/api/crm/deals/list${qs}`);
  if (!res.ok) throw new Error(`Failed to list Deal (${res.status})`);
  const json = await res.json();
  const data = (json.deals ?? json.data ?? []) as Deal[];
  const pagination = json.pagination ?? { page: 1, limit: data.length, total: data.length, totalPages: 1 };
  return { data, pagination };
}
export async function getDeal(id: string): Promise<Deal | undefined> {
  const res = await apiFetch(`/api/crm/deals/${encodeURIComponent(id)}`);
  if (!res.ok) throw new Error(`Failed to get Deal (${res.status})`);
  const json = await res.json();
  return (json.deal ?? json.data) as Deal | undefined;
}
export async function clientArchive(input: ClientArchiveInput = {}): Promise<Client | undefined> {
  const r = await executeCommand<Client>("Client", "archive", input as Record<string, unknown>);
  return r.result;
}
export async function clientCreate(input: ClientCreateInput = {}): Promise<Client | undefined> {
  const r = await executeCommand<Client>("Client", "create", input as Record<string, unknown>);
  return r.result;
}
export async function clientReactivate(input: ClientReactivateInput = {}): Promise<Client | undefined> {
  const r = await executeCommand<Client>("Client", "reactivate", input as Record<string, unknown>);
  return r.result;
}
export async function clientUpdate(input: ClientUpdateInput = {}): Promise<Client | undefined> {
  const r = await executeCommand<Client>("Client", "update", input as Record<string, unknown>);
  return r.result;
}
export async function clientContactCreate(input: ClientContactCreateInput = {}): Promise<ClientContact | undefined> {
  const r = await executeCommand<ClientContact>("ClientContact", "create", input as Record<string, unknown>);
  return r.result;
}
export async function clientContactRemove(input: ClientContactRemoveInput = {}): Promise<ClientContact | undefined> {
  const r = await executeCommand<ClientContact>("ClientContact", "remove", input as Record<string, unknown>);
  return r.result;
}
export async function clientContactSetPrimary(input: ClientContactSetPrimaryInput = {}): Promise<ClientContact | undefined> {
  const r = await executeCommand<ClientContact>("ClientContact", "setPrimary", input as Record<string, unknown>);
  return r.result;
}
export async function clientContactUpdate(input: ClientContactUpdateInput = {}): Promise<ClientContact | undefined> {
  const r = await executeCommand<ClientContact>("ClientContact", "update", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionComplete(input: ClientInteractionCompleteInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "complete", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionCreate(input: ClientInteractionCreateInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "create", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionEscalate(input: ClientInteractionEscalateInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "escalate", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionMarkOverdue(input: ClientInteractionMarkOverdueInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "markOverdue", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionSchedule(input: ClientInteractionScheduleInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "schedule", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionSoftDelete(input: ClientInteractionSoftDeleteInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "softDelete", input as Record<string, unknown>);
  return r.result;
}
export async function clientInteractionUpdate(input: ClientInteractionUpdateInput = {}): Promise<ClientInteraction | undefined> {
  const r = await executeCommand<ClientInteraction>("ClientInteraction", "update", input as Record<string, unknown>);
  return r.result;
}
export async function clientPreferenceCreate(input: ClientPreferenceCreateInput = {}): Promise<ClientPreference | undefined> {
  const r = await executeCommand<ClientPreference>("ClientPreference", "create", input as Record<string, unknown>);
  return r.result;
}
export async function clientPreferenceRemove(input: ClientPreferenceRemoveInput = {}): Promise<ClientPreference | undefined> {
  const r = await executeCommand<ClientPreference>("ClientPreference", "remove", input as Record<string, unknown>);
  return r.result;
}
export async function clientPreferenceUpdate(input: ClientPreferenceUpdateInput = {}): Promise<ClientPreference | undefined> {
  const r = await executeCommand<ClientPreference>("ClientPreference", "update", input as Record<string, unknown>);
  return r.result;
}
export async function crmScoringRuleActivate(input: CrmScoringRuleActivateInput = {}): Promise<CrmScoringRule | undefined> {
  const r = await executeCommand<CrmScoringRule>("CrmScoringRule", "activate", input as Record<string, unknown>);
  return r.result;
}
export async function crmScoringRuleCreate(input: CrmScoringRuleCreateInput = {}): Promise<CrmScoringRule | undefined> {
  const r = await executeCommand<CrmScoringRule>("CrmScoringRule", "create", input as Record<string, unknown>);
  return r.result;
}
export async function crmScoringRuleDeactivate(input: CrmScoringRuleDeactivateInput = {}): Promise<CrmScoringRule | undefined> {
  const r = await executeCommand<CrmScoringRule>("CrmScoringRule", "deactivate", input as Record<string, unknown>);
  return r.result;
}
export async function crmScoringRuleSoftDelete(input: CrmScoringRuleSoftDeleteInput = {}): Promise<CrmScoringRule | undefined> {
  const r = await executeCommand<CrmScoringRule>("CrmScoringRule", "softDelete", input as Record<string, unknown>);
  return r.result;
}
export async function crmScoringRuleUpdate(input: CrmScoringRuleUpdateInput = {}): Promise<CrmScoringRule | undefined> {
  const r = await executeCommand<CrmScoringRule>("CrmScoringRule", "update", input as Record<string, unknown>);
  return r.result;
}
export async function dealAbandon(input: DealAbandonInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "abandon", input as Record<string, unknown>);
  return r.result;
}
export async function dealAssign(input: DealAssignInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "assign", input as Record<string, unknown>);
  return r.result;
}
export async function dealClose(input: DealCloseInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "close", input as Record<string, unknown>);
  return r.result;
}
export async function dealCreate(input: DealCreateInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "create", input as Record<string, unknown>);
  return r.result;
}
export async function dealReopen(input: DealReopenInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "reopen", input as Record<string, unknown>);
  return r.result;
}
export async function dealUpdateProbability(input: DealUpdateProbabilityInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "updateProbability", input as Record<string, unknown>);
  return r.result;
}
export async function dealUpdateStage(input: DealUpdateStageInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "updateStage", input as Record<string, unknown>);
  return r.result;
}
export async function dealUpdateValue(input: DealUpdateValueInput = {}): Promise<Deal | undefined> {
  const r = await executeCommand<Deal>("Deal", "updateValue", input as Record<string, unknown>);
  return r.result;
}
export async function interactionAttachmentCreate(input: InteractionAttachmentCreateInput = {}): Promise<InteractionAttachment | undefined> {
  const r = await executeCommand<InteractionAttachment>("InteractionAttachment", "create", input as Record<string, unknown>);
  return r.result;
}
export async function interactionAttachmentRemove(input: InteractionAttachmentRemoveInput = {}): Promise<InteractionAttachment | undefined> {
  const r = await executeCommand<InteractionAttachment>("InteractionAttachment", "remove", input as Record<string, unknown>);
  return r.result;
}
export async function leadArchive(input: LeadArchiveInput = {}): Promise<Lead | undefined> {
  const r = await executeCommand<Lead>("Lead", "archive", input as Record<string, unknown>);
  return r.result;
}
export async function leadConvertToClient(input: LeadConvertToClientInput = {}): Promise<Lead | undefined> {
  const r = await executeCommand<Lead>("Lead", "convertToClient", input as Record<string, unknown>);
  return r.result;
}
export async function leadCreate(input: LeadCreateInput = {}): Promise<Lead | undefined> {
  const r = await executeCommand<Lead>("Lead", "create", input as Record<string, unknown>);
  return r.result;
}
export async function leadDisqualify(input: LeadDisqualifyInput = {}): Promise<Lead | undefined> {
  const r = await executeCommand<Lead>("Lead", "disqualify", input as Record<string, unknown>);
  return r.result;
}
export async function leadUpdate(input: LeadUpdateInput = {}): Promise<Lead | undefined> {
  const r = await executeCommand<Lead>("Lead", "update", input as Record<string, unknown>);
  return r.result;
}
export async function proposalAccept(input: ProposalAcceptInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "accept", input as Record<string, unknown>);
  return r.result;
}
export async function proposalCreate(input: ProposalCreateInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "create", input as Record<string, unknown>);
  return r.result;
}
export async function proposalDecrementLineItemCount(input: ProposalDecrementLineItemCountInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "decrementLineItemCount", input as Record<string, unknown>);
  return r.result;
}
export async function proposalGeneratePublicLink(input: ProposalGeneratePublicLinkInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "generatePublicLink", input as Record<string, unknown>);
  return r.result;
}
export async function proposalIncrementLineItemCount(input: ProposalIncrementLineItemCountInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "incrementLineItemCount", input as Record<string, unknown>);
  return r.result;
}
export async function proposalMarkViewed(input: ProposalMarkViewedInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "markViewed", input as Record<string, unknown>);
  return r.result;
}
export async function proposalReject(input: ProposalRejectInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "reject", input as Record<string, unknown>);
  return r.result;
}
export async function proposalRemove(input: ProposalRemoveInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "remove", input as Record<string, unknown>);
  return r.result;
}
export async function proposalSend(input: ProposalSendInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "send", input as Record<string, unknown>);
  return r.result;
}
export async function proposalUpdate(input: ProposalUpdateInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "update", input as Record<string, unknown>);
  return r.result;
}
export async function proposalWithdraw(input: ProposalWithdrawInput = {}): Promise<Proposal | undefined> {
  const r = await executeCommand<Proposal>("Proposal", "withdraw", input as Record<string, unknown>);
  return r.result;
}
export async function proposalLineItemCreate(input: ProposalLineItemCreateInput = {}): Promise<ProposalLineItem | undefined> {
  const r = await executeCommand<ProposalLineItem>("ProposalLineItem", "create", input as Record<string, unknown>);
  return r.result;
}
export async function proposalLineItemRemove(input: ProposalLineItemRemoveInput = {}): Promise<ProposalLineItem | undefined> {
  const r = await executeCommand<ProposalLineItem>("ProposalLineItem", "remove", input as Record<string, unknown>);
  return r.result;
}
export async function proposalLineItemUpdate(input: ProposalLineItemUpdateInput = {}): Promise<ProposalLineItem | undefined> {
  const r = await executeCommand<ProposalLineItem>("ProposalLineItem", "update", input as Record<string, unknown>);
  return r.result;
}
export async function proposalTemplateActivate(input: ProposalTemplateActivateInput = {}): Promise<ProposalTemplate | undefined> {
  const r = await executeCommand<ProposalTemplate>("ProposalTemplate", "activate", input as Record<string, unknown>);
  return r.result;
}
export async function proposalTemplateCreate(input: ProposalTemplateCreateInput = {}): Promise<ProposalTemplate | undefined> {
  const r = await executeCommand<ProposalTemplate>("ProposalTemplate", "create", input as Record<string, unknown>);
  return r.result;
}
export async function proposalTemplateDeactivate(input: ProposalTemplateDeactivateInput = {}): Promise<ProposalTemplate | undefined> {
  const r = await executeCommand<ProposalTemplate>("ProposalTemplate", "deactivate", input as Record<string, unknown>);
  return r.result;
}
export async function proposalTemplateSoftDelete(input: ProposalTemplateSoftDeleteInput = {}): Promise<ProposalTemplate | undefined> {
  const r = await executeCommand<ProposalTemplate>("ProposalTemplate", "softDelete", input as Record<string, unknown>);
  return r.result;
}
export async function proposalTemplateUpdate(input: ProposalTemplateUpdateInput = {}): Promise<ProposalTemplate | undefined> {
  const r = await executeCommand<ProposalTemplate>("ProposalTemplate", "update", input as Record<string, unknown>);
  return r.result;
}
