// GENERATED by manifest:client — DO NOT EDIT. Barrel + dynamic domain loader.
// Static re-exports are tree-shakeable; use loadClientDomain() for an async chunk.
export * from "./core.generated";
export * from "./events.generated";
export * from "./kitchen.generated";
export * from "./finance.generated";
export * from "./staffing.generated";
export * from "./crm.generated";
export * from "./logistics.generated";

/** Client domain chunk names (core holds only shared primitives). */
export type ClientDomain = "events" | "kitchen" | "finance" | "staffing" | "crm" | "logistics";
export const CLIENT_DOMAINS: readonly ClientDomain[] = [
  "events",
  "kitchen",
  "finance",
  "staffing",
  "crm",
  "logistics",
];

import type * as eventsModule from "./events.generated";
import type * as kitchenModule from "./kitchen.generated";
import type * as financeModule from "./finance.generated";
import type * as staffingModule from "./staffing.generated";
import type * as crmModule from "./crm.generated";
import type * as logisticsModule from "./logistics.generated";
interface ClientDomainModuleMap { events: typeof eventsModule; kitchen: typeof kitchenModule; finance: typeof financeModule; staffing: typeof staffingModule; crm: typeof crmModule; logistics: typeof logisticsModule; }

const DOMAIN_LOADERS: Record<ClientDomain, () => Promise<unknown>> = {
  events: () => import("./events.generated"),
  kitchen: () => import("./kitchen.generated"),
  finance: () => import("./finance.generated"),
  staffing: () => import("./staffing.generated"),
  crm: () => import("./crm.generated"),
  logistics: () => import("./logistics.generated"),
};

/** Dynamically load a domain's client chunk (creates a separate async JS bundle). */
export async function loadClientDomain<D extends ClientDomain>(domain: D): Promise<ClientDomainModuleMap[D]> {
  return DOMAIN_LOADERS[domain]() as Promise<ClientDomainModuleMap[D]>;
}
