/**
 * Typed loader for the canonical merged command registry.
 *
 * Reads manifest/runtime/commands.registry.json (generated by compile.mjs)
 * and returns a typed array of { entity, command, commandId } entries.
 *
 * This replaces the brittle relative-path JSON import previously at
 * apps/api/lib/manifest/command-resolver.ts line 15.
 *
 * resolveJsonModule is already enabled in @repo/typescript-config/base.json.
 */
import registry from "../commands.registry.json" with { type: "json" };

export interface RegistryEntry {
  entity: string;
  command: string;
  commandId: string;
}

export function getCommandsRegistry(): RegistryEntry[] {
  return registry as RegistryEntry[];
}
