/**
 * Typed loader for the DSL source-map sidecar.
 *
 * Reads `manifest/runtime/command-source-map.json` (generated by compile.mjs)
 * and exposes per-construct `.manifest` file + line locations so the runtime
 * error serializer can annotate violations with where the rule was authored.
 *
 * Mirrors the static-import pattern of `commands-registry.ts`. Keys are shaped
 * `<kind>:<Entity>[.<name>]` — `entity:Event`, `command:Event.create`,
 * `constraint:Event.validStatus`, `transition:Event.status`.
 *
 * resolveJsonModule is already enabled in @repo/typescript-config/base.json.
 */
import sourceMap from "../command-source-map.json" with { type: "json" };

export interface SourceLocation {
  /** Path to the `.manifest` file, relative to `manifest/source`. */
  file: string;
  /** 1-based line number of the declaration. */
  line: number;
}

export interface CommandSourceMap {
  entries: Record<string, SourceLocation>;
  version: number;
}

export function getCommandSourceMap(): CommandSourceMap {
  return sourceMap as CommandSourceMap;
}

/** Look up the DSL source location for a `<kind>:<Entity>[.<name>]` key. */
export function lookupSourceLocation(key: string): SourceLocation | undefined {
  return (sourceMap as CommandSourceMap).entries[key];
}
